version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: cli
    binary: ssh-ca-client-cli
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goarch:
      - amd64
      - arm64
    goos:
      - linux
      - windows
    main: ./cmd/ssh-ca-client-cli
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w -X github.com/andrewheberle/serverless-ssh-ca/client/internal/pkg/version.version={{ .Version }} -X main.Date={{ .CommitDate }}
  - id: gui
    binary: ssh-ca-client
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goarch:
      - amd64
      - arm64
    goos:
      - linux
      - windows
    main: ./cmd/ssh-ca-client
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w -X github.com/andrewheberle/serverless-ssh-ca/client/internal/pkg/version.version={{ .Version }} -X main.Date={{ .CommitDate }}
      - '{{ if eq .Os "windows" }}-H=windowsgui{{ end }}'
  - id: snap
    binary: ssh-ca-client
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    tags:
      - snap
    goarch:
      - amd64
      - arm64
    goos:
      - linux
    main: ./cmd/ssh-ca-client
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w -X github.com/andrewheberle/serverless-ssh-ca/client/internal/pkg/version.version={{ .Version }} -X main.Date={{ .CommitDate }}

archives:
  - ids:
      - cli
      - gui
    allow_different_binary_count: true
    formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - config-example.yml
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  use: github-native

checksum:
  name_template: "checksums.txt"

release:
  draft: false
  make_latest: true
  replace_existing_artifacts: true
  prerelease: auto

signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - "--bundle=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum
    output: true

nfpms:
  - ids:
      - cli
      - gui
    homepage: https://github.com/andrewheberle/ssh-ca-client
    maintainer: Andrew Heberle <andrew.heberle@gmail.com>
    description: |-
      The graphical and CLI client-side component of a Serverless SSH CA
      that handles requesting and renewing user and/or host certificates for SSH
      authentication.
    license: Apache 2.0
    formats:
      - deb
    contents:
      - src: systemd/
        dst: /usr/lib/systemd/system
    mtime: "{{ .CommitDate }}"

sboms:
  - id: package
    artifacts: package
    disable: false
  - artifacts: archive
    disable: false

snapcrafts:
  - id: snap
    ids:
      - snap
    name: ssh-ca-client
    title: Serverless SSH CA Client
    publish: false
    summary: A client for a Serverless SSH CA
    description: |
      This snap includes the graphical client-side component of a Serverless SSH CA
      that handles requesting and renewing user certificates for SSH access on your
      device.

      **Important:** This requires the deployment of the CA component on
      Cloudflare Workers, it does not work standalone.

      Please review the documentation here: https://github.com/andrewheberle/ssh-ca-client
    disable: false
    channel_templates:
      - edge
      - stable
    grade: stable
    confinement: strict
    base: core24
    license: Apache-2.0
    apps:
      ssh-ca-client:
        plugs:
          - desktop
          - desktop-legacy
          - home
          - network
          - network-bind
          - password-manager-service
    extra_files:
      - source: snap/scripts/management
        destination: bin/management
        mode: 0755
      - source: snap/hooks/configure
        destination: meta/hooks/configure
        mode: 0755
      - source: snap/hooks/post-refresh
        destination: meta/hooks/post-refresh
        mode: 0755
      - source: snap/gui
        destination: meta/gui
    layout:
      /etc/serverless-ssh-ca:
        bind: $SNAP_DATA/etc
