#!/bin/sh
#
# This utility script is used as part of the Snap build of the client
#

get_value() {
    if [ $# -ne 1 ]; then
        return 1
    fi

    v="$(snapctl get "$1")"

    if [ -z "$v" ]; then
        return 1
    fi

    echo "$v"
}

has_config_set() {
    for v in "issuer" "client-id" "scopes" "redirect-url" "ca-url"; do
        if ! get_value "$v"; then
            return $?
        fi
    done
}

issuer() {
    get_value "issuer"
}

client_id() {
    get_value "client-id"
}

scopes() {
    if ! s="$(get_value "scopes")"; then
        return $?
    fi

    if [ -z "$s" ]; then
        printf '[ "openid", "email", "profile" ]'
    fi

    echo "$s" | awk -F',' '{printf "[ "; for(i=1; i<=NF; i++) {printf "\"%s\"", $i; if(i<NF) printf ", "} printf " ]\n"}'
}

redirect_url() {
    if ! r="$(get_value "redirect-url")"; then
        return $?
    fi

    if [ -z "$r" ]; then
        printf 'http://localhost:3000/auth/callback'
    fi

    echo "$r"
}

ca_url() {
    get_value "ca-url"
}

trusted_ca() {
    get_value "trusted-ca"
}
