// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for GetCa500JSONResponseBodySuccess.
const (
	GetCa500JSONResponseBodySuccessFalse GetCa500JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetCa500JSONResponseBodySuccess enum.
func (e GetCa500JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetCa500JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostHostCertificate400JSONResponseBodySuccess.
const (
	PostHostCertificate400JSONResponseBodySuccessFalse PostHostCertificate400JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostHostCertificate400JSONResponseBodySuccess enum.
func (e PostHostCertificate400JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostHostCertificate400JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostHostCertificate401JSONResponseBodySuccess.
const (
	PostHostCertificate401JSONResponseBodySuccessFalse PostHostCertificate401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostHostCertificate401JSONResponseBodySuccess enum.
func (e PostHostCertificate401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostHostCertificate401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostHostCertificate403JSONResponseBodySuccess.
const (
	PostHostCertificate403JSONResponseBodySuccessFalse PostHostCertificate403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostHostCertificate403JSONResponseBodySuccess enum.
func (e PostHostCertificate403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostHostCertificate403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostHostCertificate422JSONResponseBodySuccess.
const (
	PostHostCertificate422JSONResponseBodySuccessFalse PostHostCertificate422JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostHostCertificate422JSONResponseBodySuccess enum.
func (e PostHostCertificate422JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostHostCertificate422JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostHostCertificate500JSONResponseBodySuccess.
const (
	PostHostCertificate500JSONResponseBodySuccessFalse PostHostCertificate500JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostHostCertificate500JSONResponseBodySuccess enum.
func (e PostHostCertificate500JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostHostCertificate500JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostHostRenew400JSONResponseBodySuccess.
const (
	PostHostRenew400JSONResponseBodySuccessFalse PostHostRenew400JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostHostRenew400JSONResponseBodySuccess enum.
func (e PostHostRenew400JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostHostRenew400JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostHostRenew401JSONResponseBodySuccess.
const (
	PostHostRenew401JSONResponseBodySuccessFalse PostHostRenew401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostHostRenew401JSONResponseBodySuccess enum.
func (e PostHostRenew401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostHostRenew401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostHostRenew403JSONResponseBodySuccess.
const (
	PostHostRenew403JSONResponseBodySuccessFalse PostHostRenew403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostHostRenew403JSONResponseBodySuccess enum.
func (e PostHostRenew403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostHostRenew403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostHostRenew422JSONResponseBodySuccess.
const (
	PostHostRenew422JSONResponseBodySuccessFalse PostHostRenew422JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostHostRenew422JSONResponseBodySuccess enum.
func (e PostHostRenew422JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostHostRenew422JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostHostRenew500JSONResponseBodySuccess.
const (
	PostHostRenew500JSONResponseBodySuccessFalse PostHostRenew500JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostHostRenew500JSONResponseBodySuccess enum.
func (e PostHostRenew500JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostHostRenew500JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostUserCertificate400JSONResponseBodySuccess.
const (
	PostUserCertificate400JSONResponseBodySuccessFalse PostUserCertificate400JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostUserCertificate400JSONResponseBodySuccess enum.
func (e PostUserCertificate400JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostUserCertificate400JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostUserCertificate401JSONResponseBodySuccess.
const (
	PostUserCertificate401JSONResponseBodySuccessFalse PostUserCertificate401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostUserCertificate401JSONResponseBodySuccess enum.
func (e PostUserCertificate401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostUserCertificate401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostUserCertificate403JSONResponseBodySuccess.
const (
	PostUserCertificate403JSONResponseBodySuccessFalse PostUserCertificate403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostUserCertificate403JSONResponseBodySuccess enum.
func (e PostUserCertificate403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostUserCertificate403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostUserCertificate422JSONResponseBodySuccess.
const (
	PostUserCertificate422JSONResponseBodySuccessFalse PostUserCertificate422JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostUserCertificate422JSONResponseBodySuccess enum.
func (e PostUserCertificate422JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostUserCertificate422JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostUserCertificate500JSONResponseBodySuccess.
const (
	PostUserCertificate500JSONResponseBodySuccessFalse PostUserCertificate500JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostUserCertificate500JSONResponseBodySuccess enum.
func (e PostUserCertificate500JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostUserCertificate500JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for GetCertificateTypeKrlParamsCertificateType.
const (
	GetCertificateTypeKrlParamsCertificateTypeHost GetCertificateTypeKrlParamsCertificateType = "host"
	GetCertificateTypeKrlParamsCertificateTypeUser GetCertificateTypeKrlParamsCertificateType = "user"
)

// Valid indicates whether the value is a known member of the GetCertificateTypeKrlParamsCertificateType enum.
func (e GetCertificateTypeKrlParamsCertificateType) Valid() bool {
	switch e {
	case GetCertificateTypeKrlParamsCertificateTypeHost:
		return true
	case GetCertificateTypeKrlParamsCertificateTypeUser:
		return true
	default:
		return false
	}
}

// Defines values for GetCertificateTypeKrl500JSONResponseBodySuccess.
const (
	GetCertificateTypeKrl500JSONResponseBodySuccessFalse GetCertificateTypeKrl500JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the GetCertificateTypeKrl500JSONResponseBodySuccess enum.
func (e GetCertificateTypeKrl500JSONResponseBodySuccess) Valid() bool {
	switch e {
	case GetCertificateTypeKrl500JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostCertificateTypeRevokeParamsCertificateType.
const (
	PostCertificateTypeRevokeParamsCertificateTypeHost PostCertificateTypeRevokeParamsCertificateType = "host"
	PostCertificateTypeRevokeParamsCertificateTypeUser PostCertificateTypeRevokeParamsCertificateType = "user"
)

// Valid indicates whether the value is a known member of the PostCertificateTypeRevokeParamsCertificateType enum.
func (e PostCertificateTypeRevokeParamsCertificateType) Valid() bool {
	switch e {
	case PostCertificateTypeRevokeParamsCertificateTypeHost:
		return true
	case PostCertificateTypeRevokeParamsCertificateTypeUser:
		return true
	default:
		return false
	}
}

// Defines values for PostCertificateTypeRevoke400JSONResponseBodySuccess.
const (
	PostCertificateTypeRevoke400JSONResponseBodySuccessFalse PostCertificateTypeRevoke400JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostCertificateTypeRevoke400JSONResponseBodySuccess enum.
func (e PostCertificateTypeRevoke400JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostCertificateTypeRevoke400JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostCertificateTypeRevoke401JSONResponseBodySuccess.
const (
	PostCertificateTypeRevoke401JSONResponseBodySuccessFalse PostCertificateTypeRevoke401JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostCertificateTypeRevoke401JSONResponseBodySuccess enum.
func (e PostCertificateTypeRevoke401JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostCertificateTypeRevoke401JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostCertificateTypeRevoke403JSONResponseBodySuccess.
const (
	PostCertificateTypeRevoke403JSONResponseBodySuccessFalse PostCertificateTypeRevoke403JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostCertificateTypeRevoke403JSONResponseBodySuccess enum.
func (e PostCertificateTypeRevoke403JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostCertificateTypeRevoke403JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostCertificateTypeRevoke409JSONResponseBodySuccess.
const (
	PostCertificateTypeRevoke409JSONResponseBodySuccessFalse PostCertificateTypeRevoke409JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostCertificateTypeRevoke409JSONResponseBodySuccess enum.
func (e PostCertificateTypeRevoke409JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostCertificateTypeRevoke409JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostCertificateTypeRevoke422JSONResponseBodySuccess.
const (
	PostCertificateTypeRevoke422JSONResponseBodySuccessFalse PostCertificateTypeRevoke422JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostCertificateTypeRevoke422JSONResponseBodySuccess enum.
func (e PostCertificateTypeRevoke422JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostCertificateTypeRevoke422JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// Defines values for PostCertificateTypeRevoke500JSONResponseBodySuccess.
const (
	PostCertificateTypeRevoke500JSONResponseBodySuccessFalse PostCertificateTypeRevoke500JSONResponseBodySuccess = false
)

// Valid indicates whether the value is a known member of the PostCertificateTypeRevoke500JSONResponseBodySuccess enum.
func (e PostCertificateTypeRevoke500JSONResponseBodySuccess) Valid() bool {
	switch e {
	case PostCertificateTypeRevoke500JSONResponseBodySuccessFalse:
		return true
	default:
		return false
	}
}

// CertificateResponse defines model for Certificate Response.
type CertificateResponse struct {
	// Certificate Issued Certificate
	Certificate []byte `json:"certificate"`
}

// CertificateRevocation defines model for Certificate Revocation.
type CertificateRevocation struct {
	// Proof Proof of possession comprising of ${timestamp}.${fingerprint}.${signature}
	Proof string `json:"proof"`

	// PublicKey SSH public key to sign
	PublicKey []byte `json:"public_key"`

	// Serial Serial number of certificate to revoke
	Serial string `json:"serial"`
}

// HostCertificateRenew defines model for Host Certificate Renew.
type HostCertificateRenew struct {
	// Certificate SSH certificate to renew
	Certificate []byte `json:"certificate"`

	// Lifetime Lifetime of renewed Host SSH certificate
	Lifetime *int `json:"lifetime,omitempty"`

	// Proof Proof of possession comprising of ${timestamp}.${fingerprint}.${signature}
	Proof string `json:"proof"`

	// PublicKey SSH public key to sign
	PublicKey []byte `json:"public_key"`
}

// HostCertificateRequest defines model for Host Certificate Request.
type HostCertificateRequest struct {
	// Identity Identity Token JWT from OIDC IdP
	Identity string `json:"identity"`

	// Lifetime Lifetime of issued Host SSH certificate
	Lifetime *int `json:"lifetime,omitempty"`

	// Principals List of principals to include on the issued certificate
	Principals []string `json:"principals"`

	// Proof Proof of possession comprising of ${timestamp}.${fingerprint}.${signature}
	Proof string `json:"proof"`

	// PublicKey SSH public key to sign
	PublicKey []byte `json:"public_key"`
}

// KeyRevocationListResponse defines model for Key Revocation List Response.
type KeyRevocationListResponse struct {
	// Krl Key Revocation List
	Krl       []byte `json:"krl"`
	Signature string `json:"signature"`
}

// RevocationResponse defines model for Revocation Response.
type RevocationResponse struct {
	RevokedAt time.Time `json:"revoked_at"`
}

// UserCertificateRequest defines model for User Certificate Request.
type UserCertificateRequest struct {
	// Extensions Extensions to include in the issued SSH certificate
	Extensions *[]string `json:"extensions,omitempty"`

	// Identity Identity Token JWT from OIDC IdP
	Identity string `json:"identity"`

	// Lifetime Lifetime of issued SSH certificate
	Lifetime *int `json:"lifetime,omitempty"`

	// Proof Proof of possession comprising of ${timestamp}.${fingerprint}.${signature}
	Proof string `json:"proof"`

	// PublicKey SSH public key to sign
	PublicKey []byte `json:"public_key"`
}

// GetCa500JSONResponseBodySuccess defines parameters for GetCa.
type GetCa500JSONResponseBodySuccess bool

// PostHostCertificateParams defines parameters for PostHostCertificate.
type PostHostCertificateParams struct {
	// Authorization Access Token JWT from OIDC IdP
	Authorization string `json:"Authorization"`
}

// PostHostCertificate400JSONResponseBodySuccess defines parameters for PostHostCertificate.
type PostHostCertificate400JSONResponseBodySuccess bool

// PostHostCertificate401JSONResponseBodySuccess defines parameters for PostHostCertificate.
type PostHostCertificate401JSONResponseBodySuccess bool

// PostHostCertificate403JSONResponseBodySuccess defines parameters for PostHostCertificate.
type PostHostCertificate403JSONResponseBodySuccess bool

// PostHostCertificate422JSONResponseBodySuccess defines parameters for PostHostCertificate.
type PostHostCertificate422JSONResponseBodySuccess bool

// PostHostCertificate500JSONResponseBodySuccess defines parameters for PostHostCertificate.
type PostHostCertificate500JSONResponseBodySuccess bool

// PostHostRenew400JSONResponseBodySuccess defines parameters for PostHostRenew.
type PostHostRenew400JSONResponseBodySuccess bool

// PostHostRenew401JSONResponseBodySuccess defines parameters for PostHostRenew.
type PostHostRenew401JSONResponseBodySuccess bool

// PostHostRenew403JSONResponseBodySuccess defines parameters for PostHostRenew.
type PostHostRenew403JSONResponseBodySuccess bool

// PostHostRenew422JSONResponseBodySuccess defines parameters for PostHostRenew.
type PostHostRenew422JSONResponseBodySuccess bool

// PostHostRenew500JSONResponseBodySuccess defines parameters for PostHostRenew.
type PostHostRenew500JSONResponseBodySuccess bool

// PostUserCertificateParams defines parameters for PostUserCertificate.
type PostUserCertificateParams struct {
	// Authorization Access Token JWT from OIDC IdP
	Authorization string `json:"Authorization"`
}

// PostUserCertificate400JSONResponseBodySuccess defines parameters for PostUserCertificate.
type PostUserCertificate400JSONResponseBodySuccess bool

// PostUserCertificate401JSONResponseBodySuccess defines parameters for PostUserCertificate.
type PostUserCertificate401JSONResponseBodySuccess bool

// PostUserCertificate403JSONResponseBodySuccess defines parameters for PostUserCertificate.
type PostUserCertificate403JSONResponseBodySuccess bool

// PostUserCertificate422JSONResponseBodySuccess defines parameters for PostUserCertificate.
type PostUserCertificate422JSONResponseBodySuccess bool

// PostUserCertificate500JSONResponseBodySuccess defines parameters for PostUserCertificate.
type PostUserCertificate500JSONResponseBodySuccess bool

// GetCertificateTypeKrlParamsCertificateType defines parameters for GetCertificateTypeKrl.
type GetCertificateTypeKrlParamsCertificateType string

// GetCertificateTypeKrl500JSONResponseBodySuccess defines parameters for GetCertificateTypeKrl.
type GetCertificateTypeKrl500JSONResponseBodySuccess bool

// PostCertificateTypeRevokeParamsCertificateType defines parameters for PostCertificateTypeRevoke.
type PostCertificateTypeRevokeParamsCertificateType string

// PostCertificateTypeRevoke400JSONResponseBodySuccess defines parameters for PostCertificateTypeRevoke.
type PostCertificateTypeRevoke400JSONResponseBodySuccess bool

// PostCertificateTypeRevoke401JSONResponseBodySuccess defines parameters for PostCertificateTypeRevoke.
type PostCertificateTypeRevoke401JSONResponseBodySuccess bool

// PostCertificateTypeRevoke403JSONResponseBodySuccess defines parameters for PostCertificateTypeRevoke.
type PostCertificateTypeRevoke403JSONResponseBodySuccess bool

// PostCertificateTypeRevoke409JSONResponseBodySuccess defines parameters for PostCertificateTypeRevoke.
type PostCertificateTypeRevoke409JSONResponseBodySuccess bool

// PostCertificateTypeRevoke422JSONResponseBodySuccess defines parameters for PostCertificateTypeRevoke.
type PostCertificateTypeRevoke422JSONResponseBodySuccess bool

// PostCertificateTypeRevoke500JSONResponseBodySuccess defines parameters for PostCertificateTypeRevoke.
type PostCertificateTypeRevoke500JSONResponseBodySuccess bool

// PostHostCertificateJSONRequestBody defines body for PostHostCertificate for application/json ContentType.
type PostHostCertificateJSONRequestBody = HostCertificateRequest

// PostHostRenewJSONRequestBody defines body for PostHostRenew for application/json ContentType.
type PostHostRenewJSONRequestBody = HostCertificateRenew

// PostUserCertificateJSONRequestBody defines body for PostUserCertificate for application/json ContentType.
type PostUserCertificateJSONRequestBody = UserCertificateRequest

// PostCertificateTypeRevokeJSONRequestBody defines body for PostCertificateTypeRevoke for application/json ContentType.
type PostCertificateTypeRevokeJSONRequestBody = CertificateRevocation

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// GetCa performs a GET /api/v3/ca (the `GetCa` operationId) request.
	GetCa(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostHostCertificateWithBody performs a POST /api/v3/host/certificate (the `PostHostCertificate` operationId) request,
	// with any type of body and a specified content type.
	PostHostCertificateWithBody(ctx context.Context, params *PostHostCertificateParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostHostCertificate performs a POST /api/v3/host/certificate (the `PostHostCertificate` operationId) request.
	// Takes a body of the `application/json` content type.
	PostHostCertificate(ctx context.Context, params *PostHostCertificateParams, body PostHostCertificateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostHostRenewWithBody performs a POST /api/v3/host/renew (the `PostHostRenew` operationId) request,
	// with any type of body and a specified content type.
	PostHostRenewWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostHostRenew performs a POST /api/v3/host/renew (the `PostHostRenew` operationId) request.
	// Takes a body of the `application/json` content type.
	PostHostRenew(ctx context.Context, body PostHostRenewJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostUserCertificateWithBody performs a POST /api/v3/user/certificate (the `PostUserCertificate` operationId) request,
	// with any type of body and a specified content type.
	PostUserCertificateWithBody(ctx context.Context, params *PostUserCertificateParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostUserCertificate performs a POST /api/v3/user/certificate (the `PostUserCertificate` operationId) request.
	// Takes a body of the `application/json` content type.
	PostUserCertificate(ctx context.Context, params *PostUserCertificateParams, body PostUserCertificateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCertificateTypeKrl performs a GET /api/v3/{certificateType}/krl (the `GetCertificateTypeKrl` operationId) request.
	GetCertificateTypeKrl(ctx context.Context, certificateType GetCertificateTypeKrlParamsCertificateType, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostCertificateTypeRevokeWithBody performs a POST /api/v3/{certificateType}/revoke (the `PostCertificateTypeRevoke` operationId) request,
	// with any type of body and a specified content type.
	PostCertificateTypeRevokeWithBody(ctx context.Context, certificateType PostCertificateTypeRevokeParamsCertificateType, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostCertificateTypeRevoke performs a POST /api/v3/{certificateType}/revoke (the `PostCertificateTypeRevoke` operationId) request.
	// Takes a body of the `application/json` content type.
	PostCertificateTypeRevoke(ctx context.Context, certificateType PostCertificateTypeRevokeParamsCertificateType, body PostCertificateTypeRevokeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetCa performs a GET /api/v3/ca (the `GetCa` operationId) request.
func (c *Client) GetCa(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCaRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostHostCertificateWithBody performs a POST /api/v3/host/certificate (the `PostHostCertificate` operationId) request,
// with any type of body and a specified content type.
func (c *Client) PostHostCertificateWithBody(ctx context.Context, params *PostHostCertificateParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostHostCertificateRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostHostCertificate performs a POST /api/v3/host/certificate (the `PostHostCertificate` operationId) request.
// Takes a body of the `application/json` content type.
func (c *Client) PostHostCertificate(ctx context.Context, params *PostHostCertificateParams, body PostHostCertificateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostHostCertificateRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostHostRenewWithBody performs a POST /api/v3/host/renew (the `PostHostRenew` operationId) request,
// with any type of body and a specified content type.
func (c *Client) PostHostRenewWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostHostRenewRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostHostRenew performs a POST /api/v3/host/renew (the `PostHostRenew` operationId) request.
// Takes a body of the `application/json` content type.
func (c *Client) PostHostRenew(ctx context.Context, body PostHostRenewJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostHostRenewRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostUserCertificateWithBody performs a POST /api/v3/user/certificate (the `PostUserCertificate` operationId) request,
// with any type of body and a specified content type.
func (c *Client) PostUserCertificateWithBody(ctx context.Context, params *PostUserCertificateParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostUserCertificateRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostUserCertificate performs a POST /api/v3/user/certificate (the `PostUserCertificate` operationId) request.
// Takes a body of the `application/json` content type.
func (c *Client) PostUserCertificate(ctx context.Context, params *PostUserCertificateParams, body PostUserCertificateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostUserCertificateRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetCertificateTypeKrl performs a GET /api/v3/{certificateType}/krl (the `GetCertificateTypeKrl` operationId) request.
func (c *Client) GetCertificateTypeKrl(ctx context.Context, certificateType GetCertificateTypeKrlParamsCertificateType, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCertificateTypeKrlRequest(c.Server, certificateType)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostCertificateTypeRevokeWithBody performs a POST /api/v3/{certificateType}/revoke (the `PostCertificateTypeRevoke` operationId) request,
// with any type of body and a specified content type.
func (c *Client) PostCertificateTypeRevokeWithBody(ctx context.Context, certificateType PostCertificateTypeRevokeParamsCertificateType, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCertificateTypeRevokeRequestWithBody(c.Server, certificateType, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostCertificateTypeRevoke performs a POST /api/v3/{certificateType}/revoke (the `PostCertificateTypeRevoke` operationId) request.
// Takes a body of the `application/json` content type.
func (c *Client) PostCertificateTypeRevoke(ctx context.Context, certificateType PostCertificateTypeRevokeParamsCertificateType, body PostCertificateTypeRevokeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCertificateTypeRevokeRequest(c.Server, certificateType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetCaRequest constructs an http.Request for the GetCa method
func NewGetCaRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v3/ca")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostHostCertificateRequest calls the generic PostHostCertificate builder with application/json body
func NewPostHostCertificateRequest(server string, params *PostHostCertificateParams, body PostHostCertificateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostHostCertificateRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPostHostCertificateRequestWithBody constructs an http.Request for the PostHostCertificate method, with any body, and a specified content type
func NewPostHostCertificateRequestWithBody(server string, params *PostHostCertificateParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v3/host/certificate")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

// NewPostHostRenewRequest calls the generic PostHostRenew builder with application/json body
func NewPostHostRenewRequest(server string, body PostHostRenewJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostHostRenewRequestWithBody(server, "application/json", bodyReader)
}

// NewPostHostRenewRequestWithBody constructs an http.Request for the PostHostRenew method, with any body, and a specified content type
func NewPostHostRenewRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v3/host/renew")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostUserCertificateRequest calls the generic PostUserCertificate builder with application/json body
func NewPostUserCertificateRequest(server string, params *PostUserCertificateParams, body PostUserCertificateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostUserCertificateRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPostUserCertificateRequestWithBody constructs an http.Request for the PostUserCertificate method, with any body, and a specified content type
func NewPostUserCertificateRequestWithBody(server string, params *PostUserCertificateParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v3/user/certificate")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

// NewGetCertificateTypeKrlRequest constructs an http.Request for the GetCertificateTypeKrl method
func NewGetCertificateTypeKrlRequest(server string, certificateType GetCertificateTypeKrlParamsCertificateType) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "certificateType", certificateType, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v3/%s/krl", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostCertificateTypeRevokeRequest calls the generic PostCertificateTypeRevoke builder with application/json body
func NewPostCertificateTypeRevokeRequest(server string, certificateType PostCertificateTypeRevokeParamsCertificateType, body PostCertificateTypeRevokeJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostCertificateTypeRevokeRequestWithBody(server, certificateType, "application/json", bodyReader)
}

// NewPostCertificateTypeRevokeRequestWithBody constructs an http.Request for the PostCertificateTypeRevoke method, with any body, and a specified content type
func NewPostCertificateTypeRevokeRequestWithBody(server string, certificateType PostCertificateTypeRevokeParamsCertificateType, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "certificateType", certificateType, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v3/%s/revoke", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// GetCaWithResponse performs a GET /api/v3/ca (the `GetCa` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	GetCaWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetCaResponse, error)

	// PostHostCertificateWithBodyWithResponse performs a POST /api/v3/host/certificate (the `PostHostCertificate` operationId) request,
	// with any type of body and a specified content type.
	//
	// Returns a wrapper object for the known response body format(s).
	PostHostCertificateWithBodyWithResponse(ctx context.Context, params *PostHostCertificateParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostHostCertificateResponse, error)

	// PostHostCertificateWithResponse performs a POST /api/v3/host/certificate (the `PostHostCertificate` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	PostHostCertificateWithResponse(ctx context.Context, params *PostHostCertificateParams, body PostHostCertificateJSONRequestBody, reqEditors ...RequestEditorFn) (*PostHostCertificateResponse, error)

	// PostHostRenewWithBodyWithResponse performs a POST /api/v3/host/renew (the `PostHostRenew` operationId) request,
	// with any type of body and a specified content type.
	//
	// Returns a wrapper object for the known response body format(s).
	PostHostRenewWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostHostRenewResponse, error)

	// PostHostRenewWithResponse performs a POST /api/v3/host/renew (the `PostHostRenew` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	PostHostRenewWithResponse(ctx context.Context, body PostHostRenewJSONRequestBody, reqEditors ...RequestEditorFn) (*PostHostRenewResponse, error)

	// PostUserCertificateWithBodyWithResponse performs a POST /api/v3/user/certificate (the `PostUserCertificate` operationId) request,
	// with any type of body and a specified content type.
	//
	// Returns a wrapper object for the known response body format(s).
	PostUserCertificateWithBodyWithResponse(ctx context.Context, params *PostUserCertificateParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostUserCertificateResponse, error)

	// PostUserCertificateWithResponse performs a POST /api/v3/user/certificate (the `PostUserCertificate` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	PostUserCertificateWithResponse(ctx context.Context, params *PostUserCertificateParams, body PostUserCertificateJSONRequestBody, reqEditors ...RequestEditorFn) (*PostUserCertificateResponse, error)

	// GetCertificateTypeKrlWithResponse performs a GET /api/v3/{certificateType}/krl (the `GetCertificateTypeKrl` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	GetCertificateTypeKrlWithResponse(ctx context.Context, certificateType GetCertificateTypeKrlParamsCertificateType, reqEditors ...RequestEditorFn) (*GetCertificateTypeKrlResponse, error)

	// PostCertificateTypeRevokeWithBodyWithResponse performs a POST /api/v3/{certificateType}/revoke (the `PostCertificateTypeRevoke` operationId) request,
	// with any type of body and a specified content type.
	//
	// Returns a wrapper object for the known response body format(s).
	PostCertificateTypeRevokeWithBodyWithResponse(ctx context.Context, certificateType PostCertificateTypeRevokeParamsCertificateType, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCertificateTypeRevokeResponse, error)

	// PostCertificateTypeRevokeWithResponse performs a POST /api/v3/{certificateType}/revoke (the `PostCertificateTypeRevoke` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	PostCertificateTypeRevokeWithResponse(ctx context.Context, certificateType PostCertificateTypeRevokeParamsCertificateType, body PostCertificateTypeRevokeJSONRequestBody, reqEditors ...RequestEditorFn) (*PostCertificateTypeRevokeResponse, error)
}

type GetCaResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *struct {
		Errors []struct {
			Code    float32 `json:"code"`
			Message string  `json:"message"`
		} `json:"errors"`
		Success GetCa500JSONResponseBodySuccess `json:"success"`
	}
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r GetCaResponse) GetJSON500() *struct {
	Errors []struct {
		Code    float32 `json:"code"`
		Message string  `json:"message"`
	} `json:"errors"`
	Success GetCa500JSONResponseBodySuccess `json:"success"`
} {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r GetCaResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetCaResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCaResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetCaResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostHostCertificateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *CertificateResponse
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *struct {
		Errors []struct {
			Code    float32  `json:"code"`
			Message string   `json:"message"`
			Path    []string `json:"path"`
		} `json:"errors"`
		Success PostHostCertificate400JSONResponseBodySuccess `json:"success"`
	}
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *struct {
		Errors []struct {
			Code    float32 `json:"code"`
			Message string  `json:"message"`
		} `json:"errors"`
		Success PostHostCertificate401JSONResponseBodySuccess `json:"success"`
	}
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *struct {
		Errors []struct {
			Code    float32 `json:"code"`
			Message string  `json:"message"`
		} `json:"errors"`
		Success PostHostCertificate403JSONResponseBodySuccess `json:"success"`
	}
	// JSON422 the response for an HTTP 422 `application/json` response
	JSON422 *struct {
		Errors []struct {
			Code    float32  `json:"code"`
			Message string   `json:"message"`
			Path    []string `json:"path"`
		} `json:"errors"`
		Success PostHostCertificate422JSONResponseBodySuccess `json:"success"`
	}
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *struct {
		Errors []struct {
			Code    float32 `json:"code"`
			Message string  `json:"message"`
		} `json:"errors"`
		Success PostHostCertificate500JSONResponseBodySuccess `json:"success"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r PostHostCertificateResponse) GetJSON200() *CertificateResponse {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r PostHostCertificateResponse) GetJSON400() *struct {
	Errors []struct {
		Code    float32  `json:"code"`
		Message string   `json:"message"`
		Path    []string `json:"path"`
	} `json:"errors"`
	Success PostHostCertificate400JSONResponseBodySuccess `json:"success"`
} {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r PostHostCertificateResponse) GetJSON401() *struct {
	Errors []struct {
		Code    float32 `json:"code"`
		Message string  `json:"message"`
	} `json:"errors"`
	Success PostHostCertificate401JSONResponseBodySuccess `json:"success"`
} {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r PostHostCertificateResponse) GetJSON403() *struct {
	Errors []struct {
		Code    float32 `json:"code"`
		Message string  `json:"message"`
	} `json:"errors"`
	Success PostHostCertificate403JSONResponseBodySuccess `json:"success"`
} {
	return r.JSON403
}

// GetJSON422 returns the response for an HTTP 422 `application/json` response
func (r PostHostCertificateResponse) GetJSON422() *struct {
	Errors []struct {
		Code    float32  `json:"code"`
		Message string   `json:"message"`
		Path    []string `json:"path"`
	} `json:"errors"`
	Success PostHostCertificate422JSONResponseBodySuccess `json:"success"`
} {
	return r.JSON422
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r PostHostCertificateResponse) GetJSON500() *struct {
	Errors []struct {
		Code    float32 `json:"code"`
		Message string  `json:"message"`
	} `json:"errors"`
	Success PostHostCertificate500JSONResponseBodySuccess `json:"success"`
} {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r PostHostCertificateResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostHostCertificateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostHostCertificateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostHostCertificateResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostHostRenewResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *CertificateResponse
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *struct {
		Errors []struct {
			Code    float32  `json:"code"`
			Message string   `json:"message"`
			Path    []string `json:"path"`
		} `json:"errors"`
		Success PostHostRenew400JSONResponseBodySuccess `json:"success"`
	}
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *struct {
		Errors []struct {
			Code    float32 `json:"code"`
			Message string  `json:"message"`
		} `json:"errors"`
		Success PostHostRenew401JSONResponseBodySuccess `json:"success"`
	}
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *struct {
		Errors []struct {
			Code    float32 `json:"code"`
			Message string  `json:"message"`
		} `json:"errors"`
		Success PostHostRenew403JSONResponseBodySuccess `json:"success"`
	}
	// JSON422 the response for an HTTP 422 `application/json` response
	JSON422 *struct {
		Errors []struct {
			Code    float32  `json:"code"`
			Message string   `json:"message"`
			Path    []string `json:"path"`
		} `json:"errors"`
		Success PostHostRenew422JSONResponseBodySuccess `json:"success"`
	}
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *struct {
		Errors []struct {
			Code    float32 `json:"code"`
			Message string  `json:"message"`
		} `json:"errors"`
		Success PostHostRenew500JSONResponseBodySuccess `json:"success"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r PostHostRenewResponse) GetJSON200() *CertificateResponse {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r PostHostRenewResponse) GetJSON400() *struct {
	Errors []struct {
		Code    float32  `json:"code"`
		Message string   `json:"message"`
		Path    []string `json:"path"`
	} `json:"errors"`
	Success PostHostRenew400JSONResponseBodySuccess `json:"success"`
} {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r PostHostRenewResponse) GetJSON401() *struct {
	Errors []struct {
		Code    float32 `json:"code"`
		Message string  `json:"message"`
	} `json:"errors"`
	Success PostHostRenew401JSONResponseBodySuccess `json:"success"`
} {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r PostHostRenewResponse) GetJSON403() *struct {
	Errors []struct {
		Code    float32 `json:"code"`
		Message string  `json:"message"`
	} `json:"errors"`
	Success PostHostRenew403JSONResponseBodySuccess `json:"success"`
} {
	return r.JSON403
}

// GetJSON422 returns the response for an HTTP 422 `application/json` response
func (r PostHostRenewResponse) GetJSON422() *struct {
	Errors []struct {
		Code    float32  `json:"code"`
		Message string   `json:"message"`
		Path    []string `json:"path"`
	} `json:"errors"`
	Success PostHostRenew422JSONResponseBodySuccess `json:"success"`
} {
	return r.JSON422
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r PostHostRenewResponse) GetJSON500() *struct {
	Errors []struct {
		Code    float32 `json:"code"`
		Message string  `json:"message"`
	} `json:"errors"`
	Success PostHostRenew500JSONResponseBodySuccess `json:"success"`
} {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r PostHostRenewResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostHostRenewResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostHostRenewResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostHostRenewResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostUserCertificateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *CertificateResponse
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *struct {
		Errors []struct {
			Code    float32  `json:"code"`
			Message string   `json:"message"`
			Path    []string `json:"path"`
		} `json:"errors"`
		Success PostUserCertificate400JSONResponseBodySuccess `json:"success"`
	}
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *struct {
		Errors []struct {
			Code    float32 `json:"code"`
			Message string  `json:"message"`
		} `json:"errors"`
		Success PostUserCertificate401JSONResponseBodySuccess `json:"success"`
	}
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *struct {
		Errors []struct {
			Code    float32 `json:"code"`
			Message string  `json:"message"`
		} `json:"errors"`
		Success PostUserCertificate403JSONResponseBodySuccess `json:"success"`
	}
	// JSON422 the response for an HTTP 422 `application/json` response
	JSON422 *struct {
		Errors []struct {
			Code    float32  `json:"code"`
			Message string   `json:"message"`
			Path    []string `json:"path"`
		} `json:"errors"`
		Success PostUserCertificate422JSONResponseBodySuccess `json:"success"`
	}
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *struct {
		Errors []struct {
			Code    float32 `json:"code"`
			Message string  `json:"message"`
		} `json:"errors"`
		Success PostUserCertificate500JSONResponseBodySuccess `json:"success"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r PostUserCertificateResponse) GetJSON200() *CertificateResponse {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r PostUserCertificateResponse) GetJSON400() *struct {
	Errors []struct {
		Code    float32  `json:"code"`
		Message string   `json:"message"`
		Path    []string `json:"path"`
	} `json:"errors"`
	Success PostUserCertificate400JSONResponseBodySuccess `json:"success"`
} {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r PostUserCertificateResponse) GetJSON401() *struct {
	Errors []struct {
		Code    float32 `json:"code"`
		Message string  `json:"message"`
	} `json:"errors"`
	Success PostUserCertificate401JSONResponseBodySuccess `json:"success"`
} {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r PostUserCertificateResponse) GetJSON403() *struct {
	Errors []struct {
		Code    float32 `json:"code"`
		Message string  `json:"message"`
	} `json:"errors"`
	Success PostUserCertificate403JSONResponseBodySuccess `json:"success"`
} {
	return r.JSON403
}

// GetJSON422 returns the response for an HTTP 422 `application/json` response
func (r PostUserCertificateResponse) GetJSON422() *struct {
	Errors []struct {
		Code    float32  `json:"code"`
		Message string   `json:"message"`
		Path    []string `json:"path"`
	} `json:"errors"`
	Success PostUserCertificate422JSONResponseBodySuccess `json:"success"`
} {
	return r.JSON422
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r PostUserCertificateResponse) GetJSON500() *struct {
	Errors []struct {
		Code    float32 `json:"code"`
		Message string  `json:"message"`
	} `json:"errors"`
	Success PostUserCertificate500JSONResponseBodySuccess `json:"success"`
} {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r PostUserCertificateResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostUserCertificateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostUserCertificateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostUserCertificateResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetCertificateTypeKrlResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *KeyRevocationListResponse
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *struct {
		Errors []struct {
			Code    float32 `json:"code"`
			Message string  `json:"message"`
		} `json:"errors"`
		Success GetCertificateTypeKrl500JSONResponseBodySuccess `json:"success"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetCertificateTypeKrlResponse) GetJSON200() *KeyRevocationListResponse {
	return r.JSON200
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r GetCertificateTypeKrlResponse) GetJSON500() *struct {
	Errors []struct {
		Code    float32 `json:"code"`
		Message string  `json:"message"`
	} `json:"errors"`
	Success GetCertificateTypeKrl500JSONResponseBodySuccess `json:"success"`
} {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r GetCertificateTypeKrlResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetCertificateTypeKrlResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCertificateTypeKrlResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetCertificateTypeKrlResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostCertificateTypeRevokeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *RevocationResponse
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *struct {
		Errors []struct {
			Code    float32  `json:"code"`
			Message string   `json:"message"`
			Path    []string `json:"path"`
		} `json:"errors"`
		Success PostCertificateTypeRevoke400JSONResponseBodySuccess `json:"success"`
	}
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *struct {
		Errors []struct {
			Code    float32 `json:"code"`
			Message string  `json:"message"`
		} `json:"errors"`
		Success PostCertificateTypeRevoke401JSONResponseBodySuccess `json:"success"`
	}
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *struct {
		Errors []struct {
			Code    float32 `json:"code"`
			Message string  `json:"message"`
		} `json:"errors"`
		Success PostCertificateTypeRevoke403JSONResponseBodySuccess `json:"success"`
	}
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *struct {
		Errors []struct {
			Code    float32 `json:"code"`
			Message string  `json:"message"`
		} `json:"errors"`
		Success PostCertificateTypeRevoke409JSONResponseBodySuccess `json:"success"`
	}
	// JSON422 the response for an HTTP 422 `application/json` response
	JSON422 *struct {
		Errors []struct {
			Code    float32  `json:"code"`
			Message string   `json:"message"`
			Path    []string `json:"path"`
		} `json:"errors"`
		Success PostCertificateTypeRevoke422JSONResponseBodySuccess `json:"success"`
	}
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *struct {
		Errors []struct {
			Code    float32 `json:"code"`
			Message string  `json:"message"`
		} `json:"errors"`
		Success PostCertificateTypeRevoke500JSONResponseBodySuccess `json:"success"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r PostCertificateTypeRevokeResponse) GetJSON200() *RevocationResponse {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r PostCertificateTypeRevokeResponse) GetJSON400() *struct {
	Errors []struct {
		Code    float32  `json:"code"`
		Message string   `json:"message"`
		Path    []string `json:"path"`
	} `json:"errors"`
	Success PostCertificateTypeRevoke400JSONResponseBodySuccess `json:"success"`
} {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r PostCertificateTypeRevokeResponse) GetJSON401() *struct {
	Errors []struct {
		Code    float32 `json:"code"`
		Message string  `json:"message"`
	} `json:"errors"`
	Success PostCertificateTypeRevoke401JSONResponseBodySuccess `json:"success"`
} {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r PostCertificateTypeRevokeResponse) GetJSON403() *struct {
	Errors []struct {
		Code    float32 `json:"code"`
		Message string  `json:"message"`
	} `json:"errors"`
	Success PostCertificateTypeRevoke403JSONResponseBodySuccess `json:"success"`
} {
	return r.JSON403
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r PostCertificateTypeRevokeResponse) GetJSON409() *struct {
	Errors []struct {
		Code    float32 `json:"code"`
		Message string  `json:"message"`
	} `json:"errors"`
	Success PostCertificateTypeRevoke409JSONResponseBodySuccess `json:"success"`
} {
	return r.JSON409
}

// GetJSON422 returns the response for an HTTP 422 `application/json` response
func (r PostCertificateTypeRevokeResponse) GetJSON422() *struct {
	Errors []struct {
		Code    float32  `json:"code"`
		Message string   `json:"message"`
		Path    []string `json:"path"`
	} `json:"errors"`
	Success PostCertificateTypeRevoke422JSONResponseBodySuccess `json:"success"`
} {
	return r.JSON422
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r PostCertificateTypeRevokeResponse) GetJSON500() *struct {
	Errors []struct {
		Code    float32 `json:"code"`
		Message string  `json:"message"`
	} `json:"errors"`
	Success PostCertificateTypeRevoke500JSONResponseBodySuccess `json:"success"`
} {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r PostCertificateTypeRevokeResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostCertificateTypeRevokeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostCertificateTypeRevokeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostCertificateTypeRevokeResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetCaWithResponse performs a GET /api/v3/ca (the `GetCa` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) GetCaWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetCaResponse, error) {
	rsp, err := c.GetCa(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCaResponse(rsp)
}

// PostHostCertificateWithBodyWithResponse performs a POST /api/v3/host/certificate (the `PostHostCertificate` operationId) request,
// with any type of body and a specified content type.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) PostHostCertificateWithBodyWithResponse(ctx context.Context, params *PostHostCertificateParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostHostCertificateResponse, error) {
	rsp, err := c.PostHostCertificateWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostHostCertificateResponse(rsp)
}

// PostHostCertificateWithResponse performs a POST /api/v3/host/certificate (the `PostHostCertificate` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) PostHostCertificateWithResponse(ctx context.Context, params *PostHostCertificateParams, body PostHostCertificateJSONRequestBody, reqEditors ...RequestEditorFn) (*PostHostCertificateResponse, error) {
	rsp, err := c.PostHostCertificate(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostHostCertificateResponse(rsp)
}

// PostHostRenewWithBodyWithResponse performs a POST /api/v3/host/renew (the `PostHostRenew` operationId) request,
// with any type of body and a specified content type.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) PostHostRenewWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostHostRenewResponse, error) {
	rsp, err := c.PostHostRenewWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostHostRenewResponse(rsp)
}

// PostHostRenewWithResponse performs a POST /api/v3/host/renew (the `PostHostRenew` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) PostHostRenewWithResponse(ctx context.Context, body PostHostRenewJSONRequestBody, reqEditors ...RequestEditorFn) (*PostHostRenewResponse, error) {
	rsp, err := c.PostHostRenew(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostHostRenewResponse(rsp)
}

// PostUserCertificateWithBodyWithResponse performs a POST /api/v3/user/certificate (the `PostUserCertificate` operationId) request,
// with any type of body and a specified content type.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) PostUserCertificateWithBodyWithResponse(ctx context.Context, params *PostUserCertificateParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostUserCertificateResponse, error) {
	rsp, err := c.PostUserCertificateWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostUserCertificateResponse(rsp)
}

// PostUserCertificateWithResponse performs a POST /api/v3/user/certificate (the `PostUserCertificate` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) PostUserCertificateWithResponse(ctx context.Context, params *PostUserCertificateParams, body PostUserCertificateJSONRequestBody, reqEditors ...RequestEditorFn) (*PostUserCertificateResponse, error) {
	rsp, err := c.PostUserCertificate(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostUserCertificateResponse(rsp)
}

// GetCertificateTypeKrlWithResponse performs a GET /api/v3/{certificateType}/krl (the `GetCertificateTypeKrl` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) GetCertificateTypeKrlWithResponse(ctx context.Context, certificateType GetCertificateTypeKrlParamsCertificateType, reqEditors ...RequestEditorFn) (*GetCertificateTypeKrlResponse, error) {
	rsp, err := c.GetCertificateTypeKrl(ctx, certificateType, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCertificateTypeKrlResponse(rsp)
}

// PostCertificateTypeRevokeWithBodyWithResponse performs a POST /api/v3/{certificateType}/revoke (the `PostCertificateTypeRevoke` operationId) request,
// with any type of body and a specified content type.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) PostCertificateTypeRevokeWithBodyWithResponse(ctx context.Context, certificateType PostCertificateTypeRevokeParamsCertificateType, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCertificateTypeRevokeResponse, error) {
	rsp, err := c.PostCertificateTypeRevokeWithBody(ctx, certificateType, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCertificateTypeRevokeResponse(rsp)
}

// PostCertificateTypeRevokeWithResponse performs a POST /api/v3/{certificateType}/revoke (the `PostCertificateTypeRevoke` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) PostCertificateTypeRevokeWithResponse(ctx context.Context, certificateType PostCertificateTypeRevokeParamsCertificateType, body PostCertificateTypeRevokeJSONRequestBody, reqEditors ...RequestEditorFn) (*PostCertificateTypeRevokeResponse, error) {
	rsp, err := c.PostCertificateTypeRevoke(ctx, certificateType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCertificateTypeRevokeResponse(rsp)
}

// ParseGetCaResponse parses an HTTP response from a GetCaWithResponse call
func ParseGetCaResponse(rsp *http.Response) (*GetCaResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCaResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Errors []struct {
				Code    float32 `json:"code"`
				Message string  `json:"message"`
			} `json:"errors"`
			Success GetCa500JSONResponseBodySuccess `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostHostCertificateResponse parses an HTTP response from a PostHostCertificateWithResponse call
func ParsePostHostCertificateResponse(rsp *http.Response) (*PostHostCertificateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostHostCertificateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CertificateResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Errors []struct {
				Code    float32  `json:"code"`
				Message string   `json:"message"`
				Path    []string `json:"path"`
			} `json:"errors"`
			Success PostHostCertificate400JSONResponseBodySuccess `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Errors []struct {
				Code    float32 `json:"code"`
				Message string  `json:"message"`
			} `json:"errors"`
			Success PostHostCertificate401JSONResponseBodySuccess `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Errors []struct {
				Code    float32 `json:"code"`
				Message string  `json:"message"`
			} `json:"errors"`
			Success PostHostCertificate403JSONResponseBodySuccess `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest struct {
			Errors []struct {
				Code    float32  `json:"code"`
				Message string   `json:"message"`
				Path    []string `json:"path"`
			} `json:"errors"`
			Success PostHostCertificate422JSONResponseBodySuccess `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Errors []struct {
				Code    float32 `json:"code"`
				Message string  `json:"message"`
			} `json:"errors"`
			Success PostHostCertificate500JSONResponseBodySuccess `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostHostRenewResponse parses an HTTP response from a PostHostRenewWithResponse call
func ParsePostHostRenewResponse(rsp *http.Response) (*PostHostRenewResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostHostRenewResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CertificateResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Errors []struct {
				Code    float32  `json:"code"`
				Message string   `json:"message"`
				Path    []string `json:"path"`
			} `json:"errors"`
			Success PostHostRenew400JSONResponseBodySuccess `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Errors []struct {
				Code    float32 `json:"code"`
				Message string  `json:"message"`
			} `json:"errors"`
			Success PostHostRenew401JSONResponseBodySuccess `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Errors []struct {
				Code    float32 `json:"code"`
				Message string  `json:"message"`
			} `json:"errors"`
			Success PostHostRenew403JSONResponseBodySuccess `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest struct {
			Errors []struct {
				Code    float32  `json:"code"`
				Message string   `json:"message"`
				Path    []string `json:"path"`
			} `json:"errors"`
			Success PostHostRenew422JSONResponseBodySuccess `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Errors []struct {
				Code    float32 `json:"code"`
				Message string  `json:"message"`
			} `json:"errors"`
			Success PostHostRenew500JSONResponseBodySuccess `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostUserCertificateResponse parses an HTTP response from a PostUserCertificateWithResponse call
func ParsePostUserCertificateResponse(rsp *http.Response) (*PostUserCertificateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostUserCertificateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CertificateResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Errors []struct {
				Code    float32  `json:"code"`
				Message string   `json:"message"`
				Path    []string `json:"path"`
			} `json:"errors"`
			Success PostUserCertificate400JSONResponseBodySuccess `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Errors []struct {
				Code    float32 `json:"code"`
				Message string  `json:"message"`
			} `json:"errors"`
			Success PostUserCertificate401JSONResponseBodySuccess `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Errors []struct {
				Code    float32 `json:"code"`
				Message string  `json:"message"`
			} `json:"errors"`
			Success PostUserCertificate403JSONResponseBodySuccess `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest struct {
			Errors []struct {
				Code    float32  `json:"code"`
				Message string   `json:"message"`
				Path    []string `json:"path"`
			} `json:"errors"`
			Success PostUserCertificate422JSONResponseBodySuccess `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Errors []struct {
				Code    float32 `json:"code"`
				Message string  `json:"message"`
			} `json:"errors"`
			Success PostUserCertificate500JSONResponseBodySuccess `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetCertificateTypeKrlResponse parses an HTTP response from a GetCertificateTypeKrlWithResponse call
func ParseGetCertificateTypeKrlResponse(rsp *http.Response) (*GetCertificateTypeKrlResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCertificateTypeKrlResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest KeyRevocationListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Errors []struct {
				Code    float32 `json:"code"`
				Message string  `json:"message"`
			} `json:"errors"`
			Success GetCertificateTypeKrl500JSONResponseBodySuccess `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostCertificateTypeRevokeResponse parses an HTTP response from a PostCertificateTypeRevokeWithResponse call
func ParsePostCertificateTypeRevokeResponse(rsp *http.Response) (*PostCertificateTypeRevokeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostCertificateTypeRevokeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RevocationResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Errors []struct {
				Code    float32  `json:"code"`
				Message string   `json:"message"`
				Path    []string `json:"path"`
			} `json:"errors"`
			Success PostCertificateTypeRevoke400JSONResponseBodySuccess `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Errors []struct {
				Code    float32 `json:"code"`
				Message string  `json:"message"`
			} `json:"errors"`
			Success PostCertificateTypeRevoke401JSONResponseBodySuccess `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Errors []struct {
				Code    float32 `json:"code"`
				Message string  `json:"message"`
			} `json:"errors"`
			Success PostCertificateTypeRevoke403JSONResponseBodySuccess `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest struct {
			Errors []struct {
				Code    float32 `json:"code"`
				Message string  `json:"message"`
			} `json:"errors"`
			Success PostCertificateTypeRevoke409JSONResponseBodySuccess `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest struct {
			Errors []struct {
				Code    float32  `json:"code"`
				Message string   `json:"message"`
				Path    []string `json:"path"`
			} `json:"errors"`
			Success PostCertificateTypeRevoke422JSONResponseBodySuccess `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Errors []struct {
				Code    float32 `json:"code"`
				Message string  `json:"message"`
			} `json:"errors"`
			Success PostCertificateTypeRevoke500JSONResponseBodySuccess `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
