// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	OidcAuthScopes = "oidcAuth.Scopes"
)

// Defines values for GetRevocationListEndpointParamsCertificateType.
const (
	GetRevocationListEndpointParamsCertificateTypeHost GetRevocationListEndpointParamsCertificateType = "host"
	GetRevocationListEndpointParamsCertificateTypeUser GetRevocationListEndpointParamsCertificateType = "user"
)

// Valid indicates whether the value is a known member of the GetRevocationListEndpointParamsCertificateType enum.
func (e GetRevocationListEndpointParamsCertificateType) Valid() bool {
	switch e {
	case GetRevocationListEndpointParamsCertificateTypeHost:
		return true
	case GetRevocationListEndpointParamsCertificateTypeUser:
		return true
	default:
		return false
	}
}

// Defines values for PostRevokeCertificateEndpointParamsCertificateType.
const (
	PostRevokeCertificateEndpointParamsCertificateTypeHost PostRevokeCertificateEndpointParamsCertificateType = "host"
	PostRevokeCertificateEndpointParamsCertificateTypeUser PostRevokeCertificateEndpointParamsCertificateType = "user"
)

// Valid indicates whether the value is a known member of the PostRevokeCertificateEndpointParamsCertificateType enum.
func (e PostRevokeCertificateEndpointParamsCertificateType) Valid() bool {
	switch e {
	case PostRevokeCertificateEndpointParamsCertificateTypeHost:
		return true
	case PostRevokeCertificateEndpointParamsCertificateTypeUser:
		return true
	default:
		return false
	}
}

// CertificateResponse defines model for Certificate Response.
type CertificateResponse struct {
	// Certificate Issued Certificate
	Certificate []byte `json:"certificate"`
}

// CertificateRevocation defines model for Certificate Revocation.
type CertificateRevocation struct {
	// Proof Proof of possession comprising of ${timestamp}.${fingerprint}.${signature}
	Proof string `json:"proof"`

	// PublicKey SSH public key to sign
	PublicKey []byte `json:"public_key"`

	// Serial Serial number of certificate to revoke
	Serial string `json:"serial"`
}

// HostCertificateRenew defines model for Host Certificate Renew.
type HostCertificateRenew struct {
	// Certificate SSH certificate to renew
	Certificate []byte `json:"certificate"`

	// Lifetime Lifetime of renewed Host SSH certificate
	Lifetime *int `json:"lifetime,omitempty"`

	// Proof Proof of possession comprising of ${timestamp}.${fingerprint}.${signature}
	Proof string `json:"proof"`

	// PublicKey SSH public key to sign
	PublicKey []byte `json:"public_key"`
}

// HostCertificateRequest defines model for Host Certificate Request.
type HostCertificateRequest struct {
	// Identity Identity Token JWT from OIDC IdP
	Identity string `json:"identity"`

	// Lifetime Lifetime of issued Host SSH certificate
	Lifetime *int `json:"lifetime,omitempty"`

	// Principals List of principals to include on the issued certificate
	Principals []string `json:"principals"`

	// Proof Proof of possession comprising of ${timestamp}.${fingerprint}.${signature}
	Proof string `json:"proof"`

	// PublicKey SSH public key to sign
	PublicKey []byte `json:"public_key"`
}

// KeyRevocationListResponse defines model for Key Revocation List Response.
type KeyRevocationListResponse struct {
	// Krl Key Revocation List
	Krl       []byte `json:"krl"`
	Signature string `json:"signature"`
}

// RevocationResponse defines model for Revocation Response.
type RevocationResponse struct {
	RevokedAt time.Time `json:"revoked_at"`
}

// UserCertificateRequest defines model for User Certificate Request.
type UserCertificateRequest struct {
	// Extensions Extensions to include in the issued SSH certificate
	Extensions *[]string `json:"extensions,omitempty"`

	// Identity Identity Token JWT from OIDC IdP
	Identity string `json:"identity"`

	// Lifetime Lifetime of issued SSH certificate
	Lifetime *int `json:"lifetime,omitempty"`

	// Proof Proof of possession comprising of ${timestamp}.${fingerprint}.${signature}
	Proof string `json:"proof"`

	// PublicKey SSH public key to sign
	PublicKey []byte `json:"public_key"`
}

// PostCertificateRequestEndpointV2JSONBody defines parameters for PostCertificateRequestEndpointV2.
type PostCertificateRequestEndpointV2JSONBody struct {
	// Extensions Extensions to include in issued SSH certificate in seconds
	Extensions *[]string `json:"extensions,omitempty"`

	// Identity Identity Token JWT from OIDC IdP
	Identity string `json:"identity"`

	// Lifetime Lifetime of issued SSH certificate
	Lifetime *float32 `json:"lifetime,omitempty"`

	// Nonce Proof of possession comprising of ${timestamp}.${fingerprint}.${format}:${signature}
	Nonce string `json:"nonce"`

	// PublicKey SSH public key to sign
	PublicKey string `json:"public_key"`
}

// PostCertificateRequestEndpointV2Params defines parameters for PostCertificateRequestEndpointV2.
type PostCertificateRequestEndpointV2Params struct {
	// Authorization Access Token JWT from OIDC IdP
	Authorization string `json:"Authorization"`
}

// PostHostCertificateRenewEndpointV2JSONBody defines parameters for PostHostCertificateRenewEndpointV2.
type PostHostCertificateRenewEndpointV2JSONBody struct {
	// Certificate SSH certificate to renew
	Certificate string `json:"certificate"`

	// Lifetime Lifetime of renewed Host SSH certificate
	Lifetime *float32 `json:"lifetime,omitempty"`

	// Nonce Proof of possession comprising of ${timestamp}.${keyfingerprint}.${format}:${signature}
	Nonce string `json:"nonce"`

	// PublicKey SSH public key of certificate to be renewed
	PublicKey string `json:"public_key"`
}

// PostHostCertificateRequestEndpointV2JSONBody defines parameters for PostHostCertificateRequestEndpointV2.
type PostHostCertificateRequestEndpointV2JSONBody struct {
	// Lifetime Lifetime of issued Host SSH certificate
	Lifetime *float32 `json:"lifetime,omitempty"`

	// Nonce Proof of possession comprising of ${timestamp}.${fingerprint}.${format}:${signature}
	Nonce string `json:"nonce"`

	// Principals List of principals to include on the issued certificate
	Principals []string `json:"principals"`

	// PublicKey SSH public key to sign
	PublicKey string `json:"public_key"`
}

// PostHostCertificateRequestEndpointV2Params defines parameters for PostHostCertificateRequestEndpointV2.
type PostHostCertificateRequestEndpointV2Params struct {
	// Authorization Access Token JWT from OIDC IdP
	Authorization string `json:"Authorization"`
}

// PostHostCertificateRequestEndpointParams defines parameters for PostHostCertificateRequestEndpoint.
type PostHostCertificateRequestEndpointParams struct {
	// Authorization Access Token JWT from OIDC IdP
	Authorization string `json:"Authorization"`
}

// PostUserCertificateRequestEndpointParams defines parameters for PostUserCertificateRequestEndpoint.
type PostUserCertificateRequestEndpointParams struct {
	// Authorization Access Token JWT from OIDC IdP
	Authorization string `json:"Authorization"`
}

// GetRevocationListEndpointParamsCertificateType defines parameters for GetRevocationListEndpoint.
type GetRevocationListEndpointParamsCertificateType string

// PostRevokeCertificateEndpointParamsCertificateType defines parameters for PostRevokeCertificateEndpoint.
type PostRevokeCertificateEndpointParamsCertificateType string

// PostCertificateRequestEndpointV2JSONRequestBody defines body for PostCertificateRequestEndpointV2 for application/json ContentType.
type PostCertificateRequestEndpointV2JSONRequestBody PostCertificateRequestEndpointV2JSONBody

// PostHostCertificateRenewEndpointV2JSONRequestBody defines body for PostHostCertificateRenewEndpointV2 for application/json ContentType.
type PostHostCertificateRenewEndpointV2JSONRequestBody PostHostCertificateRenewEndpointV2JSONBody

// PostHostCertificateRequestEndpointV2JSONRequestBody defines body for PostHostCertificateRequestEndpointV2 for application/json ContentType.
type PostHostCertificateRequestEndpointV2JSONRequestBody PostHostCertificateRequestEndpointV2JSONBody

// PostHostCertificateRequestEndpointJSONRequestBody defines body for PostHostCertificateRequestEndpoint for application/json ContentType.
type PostHostCertificateRequestEndpointJSONRequestBody = HostCertificateRequest

// PostHostCertificateRenewEndpointJSONRequestBody defines body for PostHostCertificateRenewEndpoint for application/json ContentType.
type PostHostCertificateRenewEndpointJSONRequestBody = HostCertificateRenew

// PostUserCertificateRequestEndpointJSONRequestBody defines body for PostUserCertificateRequestEndpoint for application/json ContentType.
type PostUserCertificateRequestEndpointJSONRequestBody = UserCertificateRequest

// PostRevokeCertificateEndpointJSONRequestBody defines body for PostRevokeCertificateEndpoint for application/json ContentType.
type PostRevokeCertificateEndpointJSONRequestBody = CertificateRevocation

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetCaPublicKeyEndpointV2 request
	GetCaPublicKeyEndpointV2(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostCertificateRequestEndpointV2WithBody request with any body
	PostCertificateRequestEndpointV2WithBody(ctx context.Context, params *PostCertificateRequestEndpointV2Params, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostCertificateRequestEndpointV2(ctx context.Context, params *PostCertificateRequestEndpointV2Params, body PostCertificateRequestEndpointV2JSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostHostCertificateRenewEndpointV2WithBody request with any body
	PostHostCertificateRenewEndpointV2WithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostHostCertificateRenewEndpointV2(ctx context.Context, body PostHostCertificateRenewEndpointV2JSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostHostCertificateRequestEndpointV2WithBody request with any body
	PostHostCertificateRequestEndpointV2WithBody(ctx context.Context, params *PostHostCertificateRequestEndpointV2Params, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostHostCertificateRequestEndpointV2(ctx context.Context, params *PostHostCertificateRequestEndpointV2Params, body PostHostCertificateRequestEndpointV2JSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCaPublicKeyEndpoint request
	GetCaPublicKeyEndpoint(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostHostCertificateRequestEndpointWithBody request with any body
	PostHostCertificateRequestEndpointWithBody(ctx context.Context, params *PostHostCertificateRequestEndpointParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostHostCertificateRequestEndpoint(ctx context.Context, params *PostHostCertificateRequestEndpointParams, body PostHostCertificateRequestEndpointJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostHostCertificateRenewEndpointWithBody request with any body
	PostHostCertificateRenewEndpointWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostHostCertificateRenewEndpoint(ctx context.Context, body PostHostCertificateRenewEndpointJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostUserCertificateRequestEndpointWithBody request with any body
	PostUserCertificateRequestEndpointWithBody(ctx context.Context, params *PostUserCertificateRequestEndpointParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostUserCertificateRequestEndpoint(ctx context.Context, params *PostUserCertificateRequestEndpointParams, body PostUserCertificateRequestEndpointJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetRevocationListEndpoint request
	GetRevocationListEndpoint(ctx context.Context, certificateType GetRevocationListEndpointParamsCertificateType, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostRevokeCertificateEndpointWithBody request with any body
	PostRevokeCertificateEndpointWithBody(ctx context.Context, certificateType PostRevokeCertificateEndpointParamsCertificateType, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostRevokeCertificateEndpoint(ctx context.Context, certificateType PostRevokeCertificateEndpointParamsCertificateType, body PostRevokeCertificateEndpointJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetCaPublicKeyEndpointV2(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCaPublicKeyEndpointV2Request(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostCertificateRequestEndpointV2WithBody(ctx context.Context, params *PostCertificateRequestEndpointV2Params, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCertificateRequestEndpointV2RequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostCertificateRequestEndpointV2(ctx context.Context, params *PostCertificateRequestEndpointV2Params, body PostCertificateRequestEndpointV2JSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCertificateRequestEndpointV2Request(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostHostCertificateRenewEndpointV2WithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostHostCertificateRenewEndpointV2RequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostHostCertificateRenewEndpointV2(ctx context.Context, body PostHostCertificateRenewEndpointV2JSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostHostCertificateRenewEndpointV2Request(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostHostCertificateRequestEndpointV2WithBody(ctx context.Context, params *PostHostCertificateRequestEndpointV2Params, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostHostCertificateRequestEndpointV2RequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostHostCertificateRequestEndpointV2(ctx context.Context, params *PostHostCertificateRequestEndpointV2Params, body PostHostCertificateRequestEndpointV2JSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostHostCertificateRequestEndpointV2Request(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCaPublicKeyEndpoint(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCaPublicKeyEndpointRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostHostCertificateRequestEndpointWithBody(ctx context.Context, params *PostHostCertificateRequestEndpointParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostHostCertificateRequestEndpointRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostHostCertificateRequestEndpoint(ctx context.Context, params *PostHostCertificateRequestEndpointParams, body PostHostCertificateRequestEndpointJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostHostCertificateRequestEndpointRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostHostCertificateRenewEndpointWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostHostCertificateRenewEndpointRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostHostCertificateRenewEndpoint(ctx context.Context, body PostHostCertificateRenewEndpointJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostHostCertificateRenewEndpointRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostUserCertificateRequestEndpointWithBody(ctx context.Context, params *PostUserCertificateRequestEndpointParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostUserCertificateRequestEndpointRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostUserCertificateRequestEndpoint(ctx context.Context, params *PostUserCertificateRequestEndpointParams, body PostUserCertificateRequestEndpointJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostUserCertificateRequestEndpointRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetRevocationListEndpoint(ctx context.Context, certificateType GetRevocationListEndpointParamsCertificateType, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetRevocationListEndpointRequest(c.Server, certificateType)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostRevokeCertificateEndpointWithBody(ctx context.Context, certificateType PostRevokeCertificateEndpointParamsCertificateType, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostRevokeCertificateEndpointRequestWithBody(c.Server, certificateType, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostRevokeCertificateEndpoint(ctx context.Context, certificateType PostRevokeCertificateEndpointParamsCertificateType, body PostRevokeCertificateEndpointJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostRevokeCertificateEndpointRequest(c.Server, certificateType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetCaPublicKeyEndpointV2Request generates requests for GetCaPublicKeyEndpointV2
func NewGetCaPublicKeyEndpointV2Request(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/ca")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostCertificateRequestEndpointV2Request calls the generic PostCertificateRequestEndpointV2 builder with application/json body
func NewPostCertificateRequestEndpointV2Request(server string, params *PostCertificateRequestEndpointV2Params, body PostCertificateRequestEndpointV2JSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostCertificateRequestEndpointV2RequestWithBody(server, params, "application/json", bodyReader)
}

// NewPostCertificateRequestEndpointV2RequestWithBody generates requests for PostCertificateRequestEndpointV2 with any type of body
func NewPostCertificateRequestEndpointV2RequestWithBody(server string, params *PostCertificateRequestEndpointV2Params, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/certificate")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

// NewPostHostCertificateRenewEndpointV2Request calls the generic PostHostCertificateRenewEndpointV2 builder with application/json body
func NewPostHostCertificateRenewEndpointV2Request(server string, body PostHostCertificateRenewEndpointV2JSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostHostCertificateRenewEndpointV2RequestWithBody(server, "application/json", bodyReader)
}

// NewPostHostCertificateRenewEndpointV2RequestWithBody generates requests for PostHostCertificateRenewEndpointV2 with any type of body
func NewPostHostCertificateRenewEndpointV2RequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/host/renew")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostHostCertificateRequestEndpointV2Request calls the generic PostHostCertificateRequestEndpointV2 builder with application/json body
func NewPostHostCertificateRequestEndpointV2Request(server string, params *PostHostCertificateRequestEndpointV2Params, body PostHostCertificateRequestEndpointV2JSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostHostCertificateRequestEndpointV2RequestWithBody(server, params, "application/json", bodyReader)
}

// NewPostHostCertificateRequestEndpointV2RequestWithBody generates requests for PostHostCertificateRequestEndpointV2 with any type of body
func NewPostHostCertificateRequestEndpointV2RequestWithBody(server string, params *PostHostCertificateRequestEndpointV2Params, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/host/request")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

// NewGetCaPublicKeyEndpointRequest generates requests for GetCaPublicKeyEndpoint
func NewGetCaPublicKeyEndpointRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v3/ca")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostHostCertificateRequestEndpointRequest calls the generic PostHostCertificateRequestEndpoint builder with application/json body
func NewPostHostCertificateRequestEndpointRequest(server string, params *PostHostCertificateRequestEndpointParams, body PostHostCertificateRequestEndpointJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostHostCertificateRequestEndpointRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPostHostCertificateRequestEndpointRequestWithBody generates requests for PostHostCertificateRequestEndpoint with any type of body
func NewPostHostCertificateRequestEndpointRequestWithBody(server string, params *PostHostCertificateRequestEndpointParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v3/host/certificate")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

// NewPostHostCertificateRenewEndpointRequest calls the generic PostHostCertificateRenewEndpoint builder with application/json body
func NewPostHostCertificateRenewEndpointRequest(server string, body PostHostCertificateRenewEndpointJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostHostCertificateRenewEndpointRequestWithBody(server, "application/json", bodyReader)
}

// NewPostHostCertificateRenewEndpointRequestWithBody generates requests for PostHostCertificateRenewEndpoint with any type of body
func NewPostHostCertificateRenewEndpointRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v3/host/renew")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostUserCertificateRequestEndpointRequest calls the generic PostUserCertificateRequestEndpoint builder with application/json body
func NewPostUserCertificateRequestEndpointRequest(server string, params *PostUserCertificateRequestEndpointParams, body PostUserCertificateRequestEndpointJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostUserCertificateRequestEndpointRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPostUserCertificateRequestEndpointRequestWithBody generates requests for PostUserCertificateRequestEndpoint with any type of body
func NewPostUserCertificateRequestEndpointRequestWithBody(server string, params *PostUserCertificateRequestEndpointParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v3/user/certificate")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

// NewGetRevocationListEndpointRequest generates requests for GetRevocationListEndpoint
func NewGetRevocationListEndpointRequest(server string, certificateType GetRevocationListEndpointParamsCertificateType) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "certificateType", certificateType, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v3/%s/krl", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostRevokeCertificateEndpointRequest calls the generic PostRevokeCertificateEndpoint builder with application/json body
func NewPostRevokeCertificateEndpointRequest(server string, certificateType PostRevokeCertificateEndpointParamsCertificateType, body PostRevokeCertificateEndpointJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostRevokeCertificateEndpointRequestWithBody(server, certificateType, "application/json", bodyReader)
}

// NewPostRevokeCertificateEndpointRequestWithBody generates requests for PostRevokeCertificateEndpoint with any type of body
func NewPostRevokeCertificateEndpointRequestWithBody(server string, certificateType PostRevokeCertificateEndpointParamsCertificateType, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "certificateType", certificateType, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v3/%s/revoke", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetCaPublicKeyEndpointV2WithResponse request
	GetCaPublicKeyEndpointV2WithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetCaPublicKeyEndpointV2Response, error)

	// PostCertificateRequestEndpointV2WithBodyWithResponse request with any body
	PostCertificateRequestEndpointV2WithBodyWithResponse(ctx context.Context, params *PostCertificateRequestEndpointV2Params, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCertificateRequestEndpointV2Response, error)

	PostCertificateRequestEndpointV2WithResponse(ctx context.Context, params *PostCertificateRequestEndpointV2Params, body PostCertificateRequestEndpointV2JSONRequestBody, reqEditors ...RequestEditorFn) (*PostCertificateRequestEndpointV2Response, error)

	// PostHostCertificateRenewEndpointV2WithBodyWithResponse request with any body
	PostHostCertificateRenewEndpointV2WithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostHostCertificateRenewEndpointV2Response, error)

	PostHostCertificateRenewEndpointV2WithResponse(ctx context.Context, body PostHostCertificateRenewEndpointV2JSONRequestBody, reqEditors ...RequestEditorFn) (*PostHostCertificateRenewEndpointV2Response, error)

	// PostHostCertificateRequestEndpointV2WithBodyWithResponse request with any body
	PostHostCertificateRequestEndpointV2WithBodyWithResponse(ctx context.Context, params *PostHostCertificateRequestEndpointV2Params, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostHostCertificateRequestEndpointV2Response, error)

	PostHostCertificateRequestEndpointV2WithResponse(ctx context.Context, params *PostHostCertificateRequestEndpointV2Params, body PostHostCertificateRequestEndpointV2JSONRequestBody, reqEditors ...RequestEditorFn) (*PostHostCertificateRequestEndpointV2Response, error)

	// GetCaPublicKeyEndpointWithResponse request
	GetCaPublicKeyEndpointWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetCaPublicKeyEndpointResponse, error)

	// PostHostCertificateRequestEndpointWithBodyWithResponse request with any body
	PostHostCertificateRequestEndpointWithBodyWithResponse(ctx context.Context, params *PostHostCertificateRequestEndpointParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostHostCertificateRequestEndpointResponse, error)

	PostHostCertificateRequestEndpointWithResponse(ctx context.Context, params *PostHostCertificateRequestEndpointParams, body PostHostCertificateRequestEndpointJSONRequestBody, reqEditors ...RequestEditorFn) (*PostHostCertificateRequestEndpointResponse, error)

	// PostHostCertificateRenewEndpointWithBodyWithResponse request with any body
	PostHostCertificateRenewEndpointWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostHostCertificateRenewEndpointResponse, error)

	PostHostCertificateRenewEndpointWithResponse(ctx context.Context, body PostHostCertificateRenewEndpointJSONRequestBody, reqEditors ...RequestEditorFn) (*PostHostCertificateRenewEndpointResponse, error)

	// PostUserCertificateRequestEndpointWithBodyWithResponse request with any body
	PostUserCertificateRequestEndpointWithBodyWithResponse(ctx context.Context, params *PostUserCertificateRequestEndpointParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostUserCertificateRequestEndpointResponse, error)

	PostUserCertificateRequestEndpointWithResponse(ctx context.Context, params *PostUserCertificateRequestEndpointParams, body PostUserCertificateRequestEndpointJSONRequestBody, reqEditors ...RequestEditorFn) (*PostUserCertificateRequestEndpointResponse, error)

	// GetRevocationListEndpointWithResponse request
	GetRevocationListEndpointWithResponse(ctx context.Context, certificateType GetRevocationListEndpointParamsCertificateType, reqEditors ...RequestEditorFn) (*GetRevocationListEndpointResponse, error)

	// PostRevokeCertificateEndpointWithBodyWithResponse request with any body
	PostRevokeCertificateEndpointWithBodyWithResponse(ctx context.Context, certificateType PostRevokeCertificateEndpointParamsCertificateType, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostRevokeCertificateEndpointResponse, error)

	PostRevokeCertificateEndpointWithResponse(ctx context.Context, certificateType PostRevokeCertificateEndpointParamsCertificateType, body PostRevokeCertificateEndpointJSONRequestBody, reqEditors ...RequestEditorFn) (*PostRevokeCertificateEndpointResponse, error)
}

type GetCaPublicKeyEndpointV2Response struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON500      *struct {
		Errors []struct {
			Code    float32 `json:"code"`
			Message string  `json:"message"`
		} `json:"errors"`
		Success GetCaPublicKeyEndpointV2500Success `json:"success"`
	}
}
type GetCaPublicKeyEndpointV2500Success bool

// Status returns HTTPResponse.Status
func (r GetCaPublicKeyEndpointV2Response) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCaPublicKeyEndpointV2Response) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostCertificateRequestEndpointV2Response struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Certificate string `json:"certificate"`
	}
	JSON400 *struct {
		Errors []struct {
			Code    float32  `json:"code"`
			Message string   `json:"message"`
			Path    []string `json:"path"`
		} `json:"errors"`
		Success PostCertificateRequestEndpointV2400Success `json:"success"`
	}
	JSON401 *struct {
		Error PostCertificateRequestEndpointV2401Error `json:"error"`
	}
	JSON403 *struct {
		Errors []struct {
			Code    float32 `json:"code"`
			Message string  `json:"message"`
		} `json:"errors"`
		Success PostCertificateRequestEndpointV2403Success `json:"success"`
	}
	JSON422 *struct {
		Errors []struct {
			Code    float32  `json:"code"`
			Message string   `json:"message"`
			Path    []string `json:"path"`
		} `json:"errors"`
		Success PostCertificateRequestEndpointV2422Success `json:"success"`
	}
	JSON500 *struct {
		Errors []struct {
			Code    float32 `json:"code"`
			Message string  `json:"message"`
		} `json:"errors"`
		Success PostCertificateRequestEndpointV2500Success `json:"success"`
	}
}
type PostCertificateRequestEndpointV2400Success bool
type PostCertificateRequestEndpointV2401Error string
type PostCertificateRequestEndpointV2403Success bool
type PostCertificateRequestEndpointV2422Success bool
type PostCertificateRequestEndpointV2500Success bool

// Status returns HTTPResponse.Status
func (r PostCertificateRequestEndpointV2Response) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostCertificateRequestEndpointV2Response) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostHostCertificateRenewEndpointV2Response struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Certificate string `json:"certificate"`
	}
	JSON400 *struct {
		Errors []struct {
			Code    float32  `json:"code"`
			Message string   `json:"message"`
			Path    []string `json:"path"`
		} `json:"errors"`
		Success PostHostCertificateRenewEndpointV2400Success `json:"success"`
	}
	JSON401 *struct {
		Error  PostHostCertificateRenewEndpointV2401Error  `json:"error"`
		Status PostHostCertificateRenewEndpointV2401Status `json:"status"`
	}
	JSON403 *struct {
		Errors []struct {
			Code    float32 `json:"code"`
			Message string  `json:"message"`
		} `json:"errors"`
		Success PostHostCertificateRenewEndpointV2403Success `json:"success"`
	}
	JSON422 *struct {
		Errors []struct {
			Code    float32  `json:"code"`
			Message string   `json:"message"`
			Path    []string `json:"path"`
		} `json:"errors"`
		Success PostHostCertificateRenewEndpointV2422Success `json:"success"`
	}
	JSON500 *struct {
		Errors []struct {
			Code    float32 `json:"code"`
			Message string  `json:"message"`
		} `json:"errors"`
		Success PostHostCertificateRenewEndpointV2500Success `json:"success"`
	}
}
type PostHostCertificateRenewEndpointV2400Success bool
type PostHostCertificateRenewEndpointV2401Error string
type PostHostCertificateRenewEndpointV2401Status float32
type PostHostCertificateRenewEndpointV2403Success bool
type PostHostCertificateRenewEndpointV2422Success bool
type PostHostCertificateRenewEndpointV2500Success bool

// Status returns HTTPResponse.Status
func (r PostHostCertificateRenewEndpointV2Response) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostHostCertificateRenewEndpointV2Response) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostHostCertificateRequestEndpointV2Response struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Certificate string `json:"certificate"`
	}
	JSON400 *struct {
		Errors []struct {
			Code    float32  `json:"code"`
			Message string   `json:"message"`
			Path    []string `json:"path"`
		} `json:"errors"`
		Success PostHostCertificateRequestEndpointV2400Success `json:"success"`
	}
	JSON401 *struct {
		Error  PostHostCertificateRequestEndpointV2401Error  `json:"error"`
		Status PostHostCertificateRequestEndpointV2401Status `json:"status"`
	}
	JSON403 *struct {
		Errors []struct {
			Code    float32 `json:"code"`
			Message string  `json:"message"`
		} `json:"errors"`
		Success PostHostCertificateRequestEndpointV2403Success `json:"success"`
	}
	JSON422 *struct {
		Errors []struct {
			Code    float32  `json:"code"`
			Message string   `json:"message"`
			Path    []string `json:"path"`
		} `json:"errors"`
		Success PostHostCertificateRequestEndpointV2422Success `json:"success"`
	}
	JSON500 *struct {
		Errors []struct {
			Code    float32 `json:"code"`
			Message string  `json:"message"`
		} `json:"errors"`
		Success PostHostCertificateRequestEndpointV2500Success `json:"success"`
	}
}
type PostHostCertificateRequestEndpointV2400Success bool
type PostHostCertificateRequestEndpointV2401Error string
type PostHostCertificateRequestEndpointV2401Status float32
type PostHostCertificateRequestEndpointV2403Success bool
type PostHostCertificateRequestEndpointV2422Success bool
type PostHostCertificateRequestEndpointV2500Success bool

// Status returns HTTPResponse.Status
func (r PostHostCertificateRequestEndpointV2Response) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostHostCertificateRequestEndpointV2Response) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetCaPublicKeyEndpointResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON500      *struct {
		Errors []struct {
			Code    float32 `json:"code"`
			Message string  `json:"message"`
		} `json:"errors"`
		Success GetCaPublicKeyEndpoint500Success `json:"success"`
	}
}
type GetCaPublicKeyEndpoint500Success bool

// Status returns HTTPResponse.Status
func (r GetCaPublicKeyEndpointResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCaPublicKeyEndpointResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostHostCertificateRequestEndpointResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CertificateResponse
	JSON400      *struct {
		Errors []struct {
			Code    float32  `json:"code"`
			Message string   `json:"message"`
			Path    []string `json:"path"`
		} `json:"errors"`
		Success PostHostCertificateRequestEndpoint400Success `json:"success"`
	}
	JSON401 *struct {
		Errors []struct {
			Code    float32 `json:"code"`
			Message string  `json:"message"`
		} `json:"errors"`
		Success PostHostCertificateRequestEndpoint401Success `json:"success"`
	}
	JSON403 *struct {
		Errors []struct {
			Code    float32 `json:"code"`
			Message string  `json:"message"`
		} `json:"errors"`
		Success PostHostCertificateRequestEndpoint403Success `json:"success"`
	}
	JSON422 *struct {
		Errors []struct {
			Code    float32  `json:"code"`
			Message string   `json:"message"`
			Path    []string `json:"path"`
		} `json:"errors"`
		Success PostHostCertificateRequestEndpoint422Success `json:"success"`
	}
	JSON500 *struct {
		Errors []struct {
			Code    float32 `json:"code"`
			Message string  `json:"message"`
		} `json:"errors"`
		Success PostHostCertificateRequestEndpoint500Success `json:"success"`
	}
}
type PostHostCertificateRequestEndpoint400Success bool
type PostHostCertificateRequestEndpoint401Success bool
type PostHostCertificateRequestEndpoint403Success bool
type PostHostCertificateRequestEndpoint422Success bool
type PostHostCertificateRequestEndpoint500Success bool

// Status returns HTTPResponse.Status
func (r PostHostCertificateRequestEndpointResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostHostCertificateRequestEndpointResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostHostCertificateRenewEndpointResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CertificateResponse
	JSON400      *struct {
		Errors []struct {
			Code    float32  `json:"code"`
			Message string   `json:"message"`
			Path    []string `json:"path"`
		} `json:"errors"`
		Success PostHostCertificateRenewEndpoint400Success `json:"success"`
	}
	JSON401 *struct {
		Errors []struct {
			Code    float32 `json:"code"`
			Message string  `json:"message"`
		} `json:"errors"`
		Success PostHostCertificateRenewEndpoint401Success `json:"success"`
	}
	JSON403 *struct {
		Errors []struct {
			Code    float32 `json:"code"`
			Message string  `json:"message"`
		} `json:"errors"`
		Success PostHostCertificateRenewEndpoint403Success `json:"success"`
	}
	JSON422 *struct {
		Errors []struct {
			Code    float32  `json:"code"`
			Message string   `json:"message"`
			Path    []string `json:"path"`
		} `json:"errors"`
		Success PostHostCertificateRenewEndpoint422Success `json:"success"`
	}
	JSON500 *struct {
		Errors []struct {
			Code    float32 `json:"code"`
			Message string  `json:"message"`
		} `json:"errors"`
		Success PostHostCertificateRenewEndpoint500Success `json:"success"`
	}
}
type PostHostCertificateRenewEndpoint400Success bool
type PostHostCertificateRenewEndpoint401Success bool
type PostHostCertificateRenewEndpoint403Success bool
type PostHostCertificateRenewEndpoint422Success bool
type PostHostCertificateRenewEndpoint500Success bool

// Status returns HTTPResponse.Status
func (r PostHostCertificateRenewEndpointResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostHostCertificateRenewEndpointResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostUserCertificateRequestEndpointResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CertificateResponse
	JSON400      *struct {
		Errors []struct {
			Code    float32  `json:"code"`
			Message string   `json:"message"`
			Path    []string `json:"path"`
		} `json:"errors"`
		Success PostUserCertificateRequestEndpoint400Success `json:"success"`
	}
	JSON401 *struct {
		Errors []struct {
			Code    float32 `json:"code"`
			Message string  `json:"message"`
		} `json:"errors"`
		Success PostUserCertificateRequestEndpoint401Success `json:"success"`
	}
	JSON403 *struct {
		Errors []struct {
			Code    float32 `json:"code"`
			Message string  `json:"message"`
		} `json:"errors"`
		Success PostUserCertificateRequestEndpoint403Success `json:"success"`
	}
	JSON422 *struct {
		Errors []struct {
			Code    float32  `json:"code"`
			Message string   `json:"message"`
			Path    []string `json:"path"`
		} `json:"errors"`
		Success PostUserCertificateRequestEndpoint422Success `json:"success"`
	}
	JSON500 *struct {
		Errors []struct {
			Code    float32 `json:"code"`
			Message string  `json:"message"`
		} `json:"errors"`
		Success PostUserCertificateRequestEndpoint500Success `json:"success"`
	}
}
type PostUserCertificateRequestEndpoint400Success bool
type PostUserCertificateRequestEndpoint401Success bool
type PostUserCertificateRequestEndpoint403Success bool
type PostUserCertificateRequestEndpoint422Success bool
type PostUserCertificateRequestEndpoint500Success bool

// Status returns HTTPResponse.Status
func (r PostUserCertificateRequestEndpointResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostUserCertificateRequestEndpointResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetRevocationListEndpointResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *KeyRevocationListResponse
	JSON500      *struct {
		Errors []struct {
			Code    float32 `json:"code"`
			Message string  `json:"message"`
		} `json:"errors"`
		Success GetRevocationListEndpoint500Success `json:"success"`
	}
}
type GetRevocationListEndpoint500Success bool

// Status returns HTTPResponse.Status
func (r GetRevocationListEndpointResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetRevocationListEndpointResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostRevokeCertificateEndpointResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RevocationResponse
	JSON400      *struct {
		Errors []struct {
			Code    float32  `json:"code"`
			Message string   `json:"message"`
			Path    []string `json:"path"`
		} `json:"errors"`
		Success PostRevokeCertificateEndpoint400Success `json:"success"`
	}
	JSON401 *struct {
		Errors []struct {
			Code    float32 `json:"code"`
			Message string  `json:"message"`
		} `json:"errors"`
		Success PostRevokeCertificateEndpoint401Success `json:"success"`
	}
	JSON403 *struct {
		Errors []struct {
			Code    float32 `json:"code"`
			Message string  `json:"message"`
		} `json:"errors"`
		Success PostRevokeCertificateEndpoint403Success `json:"success"`
	}
	JSON409 *struct {
		Errors []struct {
			Code    float32 `json:"code"`
			Message string  `json:"message"`
		} `json:"errors"`
		Success PostRevokeCertificateEndpoint409Success `json:"success"`
	}
	JSON422 *struct {
		Errors []struct {
			Code    float32  `json:"code"`
			Message string   `json:"message"`
			Path    []string `json:"path"`
		} `json:"errors"`
		Success PostRevokeCertificateEndpoint422Success `json:"success"`
	}
	JSON500 *struct {
		Errors []struct {
			Code    float32 `json:"code"`
			Message string  `json:"message"`
		} `json:"errors"`
		Success PostRevokeCertificateEndpoint500Success `json:"success"`
	}
}
type PostRevokeCertificateEndpoint400Success bool
type PostRevokeCertificateEndpoint401Success bool
type PostRevokeCertificateEndpoint403Success bool
type PostRevokeCertificateEndpoint409Success bool
type PostRevokeCertificateEndpoint422Success bool
type PostRevokeCertificateEndpoint500Success bool

// Status returns HTTPResponse.Status
func (r PostRevokeCertificateEndpointResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostRevokeCertificateEndpointResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetCaPublicKeyEndpointV2WithResponse request returning *GetCaPublicKeyEndpointV2Response
func (c *ClientWithResponses) GetCaPublicKeyEndpointV2WithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetCaPublicKeyEndpointV2Response, error) {
	rsp, err := c.GetCaPublicKeyEndpointV2(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCaPublicKeyEndpointV2Response(rsp)
}

// PostCertificateRequestEndpointV2WithBodyWithResponse request with arbitrary body returning *PostCertificateRequestEndpointV2Response
func (c *ClientWithResponses) PostCertificateRequestEndpointV2WithBodyWithResponse(ctx context.Context, params *PostCertificateRequestEndpointV2Params, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCertificateRequestEndpointV2Response, error) {
	rsp, err := c.PostCertificateRequestEndpointV2WithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCertificateRequestEndpointV2Response(rsp)
}

func (c *ClientWithResponses) PostCertificateRequestEndpointV2WithResponse(ctx context.Context, params *PostCertificateRequestEndpointV2Params, body PostCertificateRequestEndpointV2JSONRequestBody, reqEditors ...RequestEditorFn) (*PostCertificateRequestEndpointV2Response, error) {
	rsp, err := c.PostCertificateRequestEndpointV2(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCertificateRequestEndpointV2Response(rsp)
}

// PostHostCertificateRenewEndpointV2WithBodyWithResponse request with arbitrary body returning *PostHostCertificateRenewEndpointV2Response
func (c *ClientWithResponses) PostHostCertificateRenewEndpointV2WithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostHostCertificateRenewEndpointV2Response, error) {
	rsp, err := c.PostHostCertificateRenewEndpointV2WithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostHostCertificateRenewEndpointV2Response(rsp)
}

func (c *ClientWithResponses) PostHostCertificateRenewEndpointV2WithResponse(ctx context.Context, body PostHostCertificateRenewEndpointV2JSONRequestBody, reqEditors ...RequestEditorFn) (*PostHostCertificateRenewEndpointV2Response, error) {
	rsp, err := c.PostHostCertificateRenewEndpointV2(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostHostCertificateRenewEndpointV2Response(rsp)
}

// PostHostCertificateRequestEndpointV2WithBodyWithResponse request with arbitrary body returning *PostHostCertificateRequestEndpointV2Response
func (c *ClientWithResponses) PostHostCertificateRequestEndpointV2WithBodyWithResponse(ctx context.Context, params *PostHostCertificateRequestEndpointV2Params, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostHostCertificateRequestEndpointV2Response, error) {
	rsp, err := c.PostHostCertificateRequestEndpointV2WithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostHostCertificateRequestEndpointV2Response(rsp)
}

func (c *ClientWithResponses) PostHostCertificateRequestEndpointV2WithResponse(ctx context.Context, params *PostHostCertificateRequestEndpointV2Params, body PostHostCertificateRequestEndpointV2JSONRequestBody, reqEditors ...RequestEditorFn) (*PostHostCertificateRequestEndpointV2Response, error) {
	rsp, err := c.PostHostCertificateRequestEndpointV2(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostHostCertificateRequestEndpointV2Response(rsp)
}

// GetCaPublicKeyEndpointWithResponse request returning *GetCaPublicKeyEndpointResponse
func (c *ClientWithResponses) GetCaPublicKeyEndpointWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetCaPublicKeyEndpointResponse, error) {
	rsp, err := c.GetCaPublicKeyEndpoint(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCaPublicKeyEndpointResponse(rsp)
}

// PostHostCertificateRequestEndpointWithBodyWithResponse request with arbitrary body returning *PostHostCertificateRequestEndpointResponse
func (c *ClientWithResponses) PostHostCertificateRequestEndpointWithBodyWithResponse(ctx context.Context, params *PostHostCertificateRequestEndpointParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostHostCertificateRequestEndpointResponse, error) {
	rsp, err := c.PostHostCertificateRequestEndpointWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostHostCertificateRequestEndpointResponse(rsp)
}

func (c *ClientWithResponses) PostHostCertificateRequestEndpointWithResponse(ctx context.Context, params *PostHostCertificateRequestEndpointParams, body PostHostCertificateRequestEndpointJSONRequestBody, reqEditors ...RequestEditorFn) (*PostHostCertificateRequestEndpointResponse, error) {
	rsp, err := c.PostHostCertificateRequestEndpoint(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostHostCertificateRequestEndpointResponse(rsp)
}

// PostHostCertificateRenewEndpointWithBodyWithResponse request with arbitrary body returning *PostHostCertificateRenewEndpointResponse
func (c *ClientWithResponses) PostHostCertificateRenewEndpointWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostHostCertificateRenewEndpointResponse, error) {
	rsp, err := c.PostHostCertificateRenewEndpointWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostHostCertificateRenewEndpointResponse(rsp)
}

func (c *ClientWithResponses) PostHostCertificateRenewEndpointWithResponse(ctx context.Context, body PostHostCertificateRenewEndpointJSONRequestBody, reqEditors ...RequestEditorFn) (*PostHostCertificateRenewEndpointResponse, error) {
	rsp, err := c.PostHostCertificateRenewEndpoint(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostHostCertificateRenewEndpointResponse(rsp)
}

// PostUserCertificateRequestEndpointWithBodyWithResponse request with arbitrary body returning *PostUserCertificateRequestEndpointResponse
func (c *ClientWithResponses) PostUserCertificateRequestEndpointWithBodyWithResponse(ctx context.Context, params *PostUserCertificateRequestEndpointParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostUserCertificateRequestEndpointResponse, error) {
	rsp, err := c.PostUserCertificateRequestEndpointWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostUserCertificateRequestEndpointResponse(rsp)
}

func (c *ClientWithResponses) PostUserCertificateRequestEndpointWithResponse(ctx context.Context, params *PostUserCertificateRequestEndpointParams, body PostUserCertificateRequestEndpointJSONRequestBody, reqEditors ...RequestEditorFn) (*PostUserCertificateRequestEndpointResponse, error) {
	rsp, err := c.PostUserCertificateRequestEndpoint(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostUserCertificateRequestEndpointResponse(rsp)
}

// GetRevocationListEndpointWithResponse request returning *GetRevocationListEndpointResponse
func (c *ClientWithResponses) GetRevocationListEndpointWithResponse(ctx context.Context, certificateType GetRevocationListEndpointParamsCertificateType, reqEditors ...RequestEditorFn) (*GetRevocationListEndpointResponse, error) {
	rsp, err := c.GetRevocationListEndpoint(ctx, certificateType, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetRevocationListEndpointResponse(rsp)
}

// PostRevokeCertificateEndpointWithBodyWithResponse request with arbitrary body returning *PostRevokeCertificateEndpointResponse
func (c *ClientWithResponses) PostRevokeCertificateEndpointWithBodyWithResponse(ctx context.Context, certificateType PostRevokeCertificateEndpointParamsCertificateType, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostRevokeCertificateEndpointResponse, error) {
	rsp, err := c.PostRevokeCertificateEndpointWithBody(ctx, certificateType, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostRevokeCertificateEndpointResponse(rsp)
}

func (c *ClientWithResponses) PostRevokeCertificateEndpointWithResponse(ctx context.Context, certificateType PostRevokeCertificateEndpointParamsCertificateType, body PostRevokeCertificateEndpointJSONRequestBody, reqEditors ...RequestEditorFn) (*PostRevokeCertificateEndpointResponse, error) {
	rsp, err := c.PostRevokeCertificateEndpoint(ctx, certificateType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostRevokeCertificateEndpointResponse(rsp)
}

// ParseGetCaPublicKeyEndpointV2Response parses an HTTP response from a GetCaPublicKeyEndpointV2WithResponse call
func ParseGetCaPublicKeyEndpointV2Response(rsp *http.Response) (*GetCaPublicKeyEndpointV2Response, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCaPublicKeyEndpointV2Response{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Errors []struct {
				Code    float32 `json:"code"`
				Message string  `json:"message"`
			} `json:"errors"`
			Success GetCaPublicKeyEndpointV2500Success `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostCertificateRequestEndpointV2Response parses an HTTP response from a PostCertificateRequestEndpointV2WithResponse call
func ParsePostCertificateRequestEndpointV2Response(rsp *http.Response) (*PostCertificateRequestEndpointV2Response, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostCertificateRequestEndpointV2Response{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Certificate string `json:"certificate"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Errors []struct {
				Code    float32  `json:"code"`
				Message string   `json:"message"`
				Path    []string `json:"path"`
			} `json:"errors"`
			Success PostCertificateRequestEndpointV2400Success `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Error PostCertificateRequestEndpointV2401Error `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Errors []struct {
				Code    float32 `json:"code"`
				Message string  `json:"message"`
			} `json:"errors"`
			Success PostCertificateRequestEndpointV2403Success `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest struct {
			Errors []struct {
				Code    float32  `json:"code"`
				Message string   `json:"message"`
				Path    []string `json:"path"`
			} `json:"errors"`
			Success PostCertificateRequestEndpointV2422Success `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Errors []struct {
				Code    float32 `json:"code"`
				Message string  `json:"message"`
			} `json:"errors"`
			Success PostCertificateRequestEndpointV2500Success `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostHostCertificateRenewEndpointV2Response parses an HTTP response from a PostHostCertificateRenewEndpointV2WithResponse call
func ParsePostHostCertificateRenewEndpointV2Response(rsp *http.Response) (*PostHostCertificateRenewEndpointV2Response, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostHostCertificateRenewEndpointV2Response{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Certificate string `json:"certificate"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Errors []struct {
				Code    float32  `json:"code"`
				Message string   `json:"message"`
				Path    []string `json:"path"`
			} `json:"errors"`
			Success PostHostCertificateRenewEndpointV2400Success `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Error  PostHostCertificateRenewEndpointV2401Error  `json:"error"`
			Status PostHostCertificateRenewEndpointV2401Status `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Errors []struct {
				Code    float32 `json:"code"`
				Message string  `json:"message"`
			} `json:"errors"`
			Success PostHostCertificateRenewEndpointV2403Success `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest struct {
			Errors []struct {
				Code    float32  `json:"code"`
				Message string   `json:"message"`
				Path    []string `json:"path"`
			} `json:"errors"`
			Success PostHostCertificateRenewEndpointV2422Success `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Errors []struct {
				Code    float32 `json:"code"`
				Message string  `json:"message"`
			} `json:"errors"`
			Success PostHostCertificateRenewEndpointV2500Success `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostHostCertificateRequestEndpointV2Response parses an HTTP response from a PostHostCertificateRequestEndpointV2WithResponse call
func ParsePostHostCertificateRequestEndpointV2Response(rsp *http.Response) (*PostHostCertificateRequestEndpointV2Response, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostHostCertificateRequestEndpointV2Response{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Certificate string `json:"certificate"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Errors []struct {
				Code    float32  `json:"code"`
				Message string   `json:"message"`
				Path    []string `json:"path"`
			} `json:"errors"`
			Success PostHostCertificateRequestEndpointV2400Success `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Error  PostHostCertificateRequestEndpointV2401Error  `json:"error"`
			Status PostHostCertificateRequestEndpointV2401Status `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Errors []struct {
				Code    float32 `json:"code"`
				Message string  `json:"message"`
			} `json:"errors"`
			Success PostHostCertificateRequestEndpointV2403Success `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest struct {
			Errors []struct {
				Code    float32  `json:"code"`
				Message string   `json:"message"`
				Path    []string `json:"path"`
			} `json:"errors"`
			Success PostHostCertificateRequestEndpointV2422Success `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Errors []struct {
				Code    float32 `json:"code"`
				Message string  `json:"message"`
			} `json:"errors"`
			Success PostHostCertificateRequestEndpointV2500Success `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetCaPublicKeyEndpointResponse parses an HTTP response from a GetCaPublicKeyEndpointWithResponse call
func ParseGetCaPublicKeyEndpointResponse(rsp *http.Response) (*GetCaPublicKeyEndpointResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCaPublicKeyEndpointResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Errors []struct {
				Code    float32 `json:"code"`
				Message string  `json:"message"`
			} `json:"errors"`
			Success GetCaPublicKeyEndpoint500Success `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostHostCertificateRequestEndpointResponse parses an HTTP response from a PostHostCertificateRequestEndpointWithResponse call
func ParsePostHostCertificateRequestEndpointResponse(rsp *http.Response) (*PostHostCertificateRequestEndpointResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostHostCertificateRequestEndpointResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CertificateResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Errors []struct {
				Code    float32  `json:"code"`
				Message string   `json:"message"`
				Path    []string `json:"path"`
			} `json:"errors"`
			Success PostHostCertificateRequestEndpoint400Success `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Errors []struct {
				Code    float32 `json:"code"`
				Message string  `json:"message"`
			} `json:"errors"`
			Success PostHostCertificateRequestEndpoint401Success `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Errors []struct {
				Code    float32 `json:"code"`
				Message string  `json:"message"`
			} `json:"errors"`
			Success PostHostCertificateRequestEndpoint403Success `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest struct {
			Errors []struct {
				Code    float32  `json:"code"`
				Message string   `json:"message"`
				Path    []string `json:"path"`
			} `json:"errors"`
			Success PostHostCertificateRequestEndpoint422Success `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Errors []struct {
				Code    float32 `json:"code"`
				Message string  `json:"message"`
			} `json:"errors"`
			Success PostHostCertificateRequestEndpoint500Success `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostHostCertificateRenewEndpointResponse parses an HTTP response from a PostHostCertificateRenewEndpointWithResponse call
func ParsePostHostCertificateRenewEndpointResponse(rsp *http.Response) (*PostHostCertificateRenewEndpointResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostHostCertificateRenewEndpointResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CertificateResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Errors []struct {
				Code    float32  `json:"code"`
				Message string   `json:"message"`
				Path    []string `json:"path"`
			} `json:"errors"`
			Success PostHostCertificateRenewEndpoint400Success `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Errors []struct {
				Code    float32 `json:"code"`
				Message string  `json:"message"`
			} `json:"errors"`
			Success PostHostCertificateRenewEndpoint401Success `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Errors []struct {
				Code    float32 `json:"code"`
				Message string  `json:"message"`
			} `json:"errors"`
			Success PostHostCertificateRenewEndpoint403Success `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest struct {
			Errors []struct {
				Code    float32  `json:"code"`
				Message string   `json:"message"`
				Path    []string `json:"path"`
			} `json:"errors"`
			Success PostHostCertificateRenewEndpoint422Success `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Errors []struct {
				Code    float32 `json:"code"`
				Message string  `json:"message"`
			} `json:"errors"`
			Success PostHostCertificateRenewEndpoint500Success `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostUserCertificateRequestEndpointResponse parses an HTTP response from a PostUserCertificateRequestEndpointWithResponse call
func ParsePostUserCertificateRequestEndpointResponse(rsp *http.Response) (*PostUserCertificateRequestEndpointResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostUserCertificateRequestEndpointResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CertificateResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Errors []struct {
				Code    float32  `json:"code"`
				Message string   `json:"message"`
				Path    []string `json:"path"`
			} `json:"errors"`
			Success PostUserCertificateRequestEndpoint400Success `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Errors []struct {
				Code    float32 `json:"code"`
				Message string  `json:"message"`
			} `json:"errors"`
			Success PostUserCertificateRequestEndpoint401Success `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Errors []struct {
				Code    float32 `json:"code"`
				Message string  `json:"message"`
			} `json:"errors"`
			Success PostUserCertificateRequestEndpoint403Success `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest struct {
			Errors []struct {
				Code    float32  `json:"code"`
				Message string   `json:"message"`
				Path    []string `json:"path"`
			} `json:"errors"`
			Success PostUserCertificateRequestEndpoint422Success `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Errors []struct {
				Code    float32 `json:"code"`
				Message string  `json:"message"`
			} `json:"errors"`
			Success PostUserCertificateRequestEndpoint500Success `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetRevocationListEndpointResponse parses an HTTP response from a GetRevocationListEndpointWithResponse call
func ParseGetRevocationListEndpointResponse(rsp *http.Response) (*GetRevocationListEndpointResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetRevocationListEndpointResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest KeyRevocationListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Errors []struct {
				Code    float32 `json:"code"`
				Message string  `json:"message"`
			} `json:"errors"`
			Success GetRevocationListEndpoint500Success `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostRevokeCertificateEndpointResponse parses an HTTP response from a PostRevokeCertificateEndpointWithResponse call
func ParsePostRevokeCertificateEndpointResponse(rsp *http.Response) (*PostRevokeCertificateEndpointResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostRevokeCertificateEndpointResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RevocationResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Errors []struct {
				Code    float32  `json:"code"`
				Message string   `json:"message"`
				Path    []string `json:"path"`
			} `json:"errors"`
			Success PostRevokeCertificateEndpoint400Success `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Errors []struct {
				Code    float32 `json:"code"`
				Message string  `json:"message"`
			} `json:"errors"`
			Success PostRevokeCertificateEndpoint401Success `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Errors []struct {
				Code    float32 `json:"code"`
				Message string  `json:"message"`
			} `json:"errors"`
			Success PostRevokeCertificateEndpoint403Success `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest struct {
			Errors []struct {
				Code    float32 `json:"code"`
				Message string  `json:"message"`
			} `json:"errors"`
			Success PostRevokeCertificateEndpoint409Success `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest struct {
			Errors []struct {
				Code    float32  `json:"code"`
				Message string   `json:"message"`
				Path    []string `json:"path"`
			} `json:"errors"`
			Success PostRevokeCertificateEndpoint422Success `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Errors []struct {
				Code    float32 `json:"code"`
				Message string  `json:"message"`
			} `json:"errors"`
			Success PostRevokeCertificateEndpoint500Success `json:"success"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
