name: Run tests and upload coverage

permissions:
  contents: read

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  test:
    name: Run Go tests and with coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: stable
          cache: false

      - name: Install Go dependencies
        run: go mod download

      - name: Run Go tests with coverage
        run: go test -coverprofile=coverage.txt ./...

      - name: Upload results to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v6.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: andrewheberle/ssh-ca-client
